<?php
require_once __DIR__ . '/../../../config/config.php'; require_once ROOT_PATH . '/includes/authentication.php'; require_once __DIR__ . '/../database/db_connect.php'; require_once __DIR__ . '/../includes/PaymentReportingScope.php'; require_once __DIR__ . '/../includes/SimpleXlsxWriter.php';
requireAuth(); requirePaymentPermission('payment.walkin_history'); $cashierId=(int)getCurrentUserId();
$period=(string)($_GET['date_range']??''); $date=''; if($period==='today')$date=' AND DATE(recorded_at)=CURDATE()'; elseif($period==='week')$date=' AND DATE(recorded_at)>=DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY)'; elseif($period==='month')$date=' AND YEAR(recorded_at)=YEAR(CURDATE()) AND MONTH(recorded_at)=MONTH(CURDATE())'; elseif($period==='year')$date=' AND YEAR(recorded_at)=YEAR(CURDATE())';
try {
 $official=PaymentReportingScope::officialCondition('p');
 $sql="SELECT 'Academic Payment' transaction_type, p.receipt_number receipt, s.student_number, s.full_name, p.amount total, p.payment_date recorded_at, p.remarks, '' items FROM payments p JOIN students s ON s.student_id=p.student_id WHERE p.transaction_type='Walk-in' AND p.payment_channel='Cash' AND p.verified_by=? AND {$official}";
 $rows=$pdo->prepare("SELECT * FROM ((SELECT 'Academic Payment' transaction_type, p.receipt_number receipt, s.student_number, s.full_name, p.amount total, p.payment_date recorded_at, p.remarks, '' items FROM payments p JOIN students s ON s.student_id=p.student_id WHERE p.transaction_type='Walk-in' AND p.payment_channel='Cash' AND p.verified_by=? AND {$official}) UNION ALL (SELECT 'School Sale', cs.receipt_number, s.student_number, s.full_name, cs.total_amount, cs.sold_at, cs.remarks, GROUP_CONCAT(CONCAT(csi.item_name_snapshot,' x',csi.quantity) SEPARATOR ', ') FROM cash_sales cs JOIN students s ON s.student_id=cs.student_id JOIN cash_sale_items csi ON csi.cash_sale_id=cs.cash_sale_id WHERE cs.cashier_id=? AND cs.sale_status='Completed' GROUP BY cs.cash_sale_id)) h WHERE 1=1" . str_replace('recorded_at', 'h.recorded_at', $date) . ' ORDER BY recorded_at DESC');
 $rows->execute([$cashierId,$cashierId]); $data=[['Transaction Type','OR Number','Student Number','Student Name','Items / Details','Amount','Date','Remarks']]; foreach($rows->fetchAll(PDO::FETCH_ASSOC) as $row)$data[]=[ $row['transaction_type'],$row['receipt'],$row['student_number'],$row['full_name'],$row['items'],$row['total'],$row['recorded_at'],$row['remarks']];
 SimpleXlsxWriter::download('cashier-history-'.date('Ymd-His').'.xlsx',$data);
} catch(Throwable $e){http_response_code(500); header('Content-Type:text/plain'); echo 'Unable to export cashier history.';}
