-- MIS-5B additive OCR foundation. Requires PASS preflight and verified payment_db backup.
-- MariaDB DDL implicitly commits; this file has not been executed.
CREATE TABLE ocr_usage_months (
 billing_month DATE NOT NULL COMMENT 'First day of Asia/Manila application month',
 configured_limit SMALLINT UNSIGNED NOT NULL,
 reserved_units SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 consumed_units SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Provider-call boundary reached',
 successful_units SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 failed_units SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Provider called but OCR failed',
 released_units INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Cumulative releases before provider call',
 row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (billing_month),
 CONSTRAINT chk_ocr_month_first_day CHECK (DAYOFMONTH(billing_month)=1),
 CONSTRAINT chk_ocr_month_limit CHECK (configured_limit>0),
 CONSTRAINT chk_ocr_month_capacity CHECK (reserved_units+consumed_units<=configured_limit),
 CONSTRAINT chk_ocr_month_outcomes CHECK (successful_units+failed_units=consumed_units)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE ocr_usage_ledger (
 usage_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 request_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'Server UUID v4 correlation ID',
 idempotency_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'Server-derived SHA-256',
 billing_month DATE NOT NULL,
 operation VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 concern_id INT UNSIGNED NULL,
 image_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
 provider VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'google_cloud_vision',
 feature VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'DOCUMENT_TEXT_DETECTION',
 feature_version VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 units SMALLINT UNSIGNED NOT NULL DEFAULT 1,
 lifecycle_state VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 provider_called TINYINT(1) NOT NULL DEFAULT 0,
 failure_category VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
 actor_user_id INT UNSIGNED NULL COMMENT 'Core user snapshot; no cross-database FK',
 reserved_at DATETIME NULL, provider_called_at DATETIME NULL, completed_at DATETIME NULL, released_at DATETIME NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (usage_id),
 UNIQUE KEY uq_ocr_usage_request (request_id),
 UNIQUE KEY uq_ocr_usage_idempotency (idempotency_key),
 KEY idx_ocr_usage_month_state (billing_month,lifecycle_state),
 KEY idx_ocr_usage_concern (concern_id,created_at),
 KEY idx_ocr_usage_image_context (image_sha256,provider,feature,feature_version),
 CONSTRAINT fk_ocr_usage_month FOREIGN KEY (billing_month) REFERENCES ocr_usage_months(billing_month),
 CONSTRAINT fk_ocr_usage_concern FOREIGN KEY (concern_id) REFERENCES payment_concerns(concern_id) ON DELETE SET NULL,
 CONSTRAINT chk_ocr_usage_request CHECK (request_id REGEXP '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
 CONSTRAINT chk_ocr_usage_idempotency CHECK (idempotency_key REGEXP '^[0-9a-f]{64}$'),
 CONSTRAINT chk_ocr_usage_hash CHECK (image_sha256 IS NULL OR image_sha256 REGEXP '^[0-9a-f]{64}$'),
 CONSTRAINT chk_ocr_usage_units CHECK (units IN (0,1)),
 CONSTRAINT chk_ocr_usage_state CHECK (lifecycle_state IN ('RESERVED','PROVIDER_CALLED','SUCCEEDED','FAILED','RELEASED','REJECTED_LIMIT','CACHE_HIT')),
 CONSTRAINT chk_ocr_usage_provider CHECK ((provider_called=0 AND provider_called_at IS NULL) OR (provider_called=1 AND provider_called_at IS NOT NULL)),
 CONSTRAINT chk_ocr_usage_cache CHECK (lifecycle_state<>'CACHE_HIT' OR (units=0 AND provider_called=0)),
 CONSTRAINT chk_ocr_usage_rejected CHECK (lifecycle_state<>'REJECTED_LIMIT' OR (units=0 AND provider_called=0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE ocr_scan_attempts (
 attempt_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 request_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 concern_id INT UNSIGNED NOT NULL,
 attempt_number INT UNSIGNED NOT NULL,
 image_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 provider VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 feature VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 feature_version VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 parser_version VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 extraction_status VARCHAR(50) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 normalized_text MEDIUMTEXT NULL COMMENT 'Normalized evidence; no full provider payload',
 extracted_amount DECIMAL(10,2) NULL, bank_name VARCHAR(100) NULL, reference_number VARCHAR(100) NULL,
 transaction_date DATE NULL, transaction_time TIME NULL, confidence_score DECIMAL(5,2) NULL,
 quality_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
 failure_category VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
 cache_hit TINYINT(1) NOT NULL DEFAULT 0,
 cache_source_attempt_id BIGINT UNSIGNED NULL,
 scanned_by INT UNSIGNED NULL COMMENT 'Core user snapshot; no cross-database FK',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at DATETIME NULL,
 PRIMARY KEY (attempt_id),
 UNIQUE KEY uq_ocr_attempt_request (request_id),
 UNIQUE KEY uq_ocr_attempt_number (concern_id,attempt_number),
 KEY idx_ocr_attempt_image_context (image_sha256,provider,feature,feature_version),
 KEY idx_ocr_attempt_status_time (extraction_status,created_at),
 KEY idx_ocr_attempt_cache_source (cache_source_attempt_id),
 CONSTRAINT fk_ocr_attempt_usage FOREIGN KEY (request_id) REFERENCES ocr_usage_ledger(request_id),
 CONSTRAINT fk_ocr_attempt_concern FOREIGN KEY (concern_id) REFERENCES payment_concerns(concern_id) ON DELETE CASCADE,
 CONSTRAINT chk_ocr_attempt_hash CHECK (image_sha256 REGEXP '^[0-9a-f]{64}$'),
 CONSTRAINT chk_ocr_attempt_number CHECK (attempt_number>0),
 CONSTRAINT chk_ocr_attempt_confidence CHECK (confidence_score IS NULL OR (confidence_score>=0 AND confidence_score<=100)),
 CONSTRAINT chk_ocr_attempt_quality CHECK (quality_json IS NULL OR JSON_VALID(quality_json)),
 CONSTRAINT chk_ocr_attempt_cache CHECK ((cache_hit=0 AND cache_source_attempt_id IS NULL) OR (cache_hit=1 AND cache_source_attempt_id IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE ocr_image_cache (
 image_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 provider VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 feature VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 feature_version VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 canonical_attempt_id BIGINT UNSIGNED NOT NULL,
 hit_count INT UNSIGNED NOT NULL DEFAULT 0,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 last_used_at DATETIME NULL,
 PRIMARY KEY (image_sha256,provider,feature,feature_version),
 KEY idx_ocr_cache_attempt (canonical_attempt_id),
 CONSTRAINT fk_ocr_cache_attempt FOREIGN KEY (canonical_attempt_id) REFERENCES ocr_scan_attempts(attempt_id) ON DELETE CASCADE,
 CONSTRAINT chk_ocr_cache_hash CHECK (image_sha256 REGEXP '^[0-9a-f]{64}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
