-- MIS-5B completion after verified partial import. Existing months/ledger are preserved.
CREATE TABLE ocr_scan_attempts (
 attempt_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 request_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 concern_id INT UNSIGNED NOT NULL,
 attempt_number INT UNSIGNED NOT NULL,
 image_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 provider VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 feature VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 feature_version VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 parser_version VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 extraction_status VARCHAR(50) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 normalized_text MEDIUMTEXT NULL COMMENT 'Normalized evidence; no full provider payload',
 extracted_amount DECIMAL(10,2) NULL, bank_name VARCHAR(100) NULL, reference_number VARCHAR(100) NULL,
 transaction_date DATE NULL, transaction_time TIME NULL, confidence_score DECIMAL(5,2) NULL,
 quality_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
 failure_category VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
 cache_hit TINYINT(1) NOT NULL DEFAULT 0,
 cache_source_attempt_id BIGINT UNSIGNED NULL,
 scanned_by INT UNSIGNED NULL COMMENT 'Core user snapshot; no cross-database FK',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at DATETIME NULL,
 PRIMARY KEY (attempt_id),
 UNIQUE KEY uq_ocr_attempt_request (request_id),
 UNIQUE KEY uq_ocr_attempt_number (concern_id,attempt_number),
 KEY idx_ocr_attempt_image_context (image_sha256,provider,feature,feature_version),
 KEY idx_ocr_attempt_status_time (extraction_status,created_at),
 KEY idx_ocr_attempt_cache_source (cache_source_attempt_id),
 CONSTRAINT fk_ocr_attempt_usage FOREIGN KEY (request_id) REFERENCES ocr_usage_ledger(request_id),
 CONSTRAINT fk_ocr_attempt_concern FOREIGN KEY (concern_id) REFERENCES payment_concerns(concern_id) ON DELETE CASCADE,
 CONSTRAINT chk_ocr_attempt_hash CHECK (image_sha256 REGEXP '^[0-9a-f]{64}$'),
 CONSTRAINT chk_ocr_attempt_number CHECK (attempt_number>0),
 CONSTRAINT chk_ocr_attempt_confidence CHECK (confidence_score IS NULL OR (confidence_score>=0 AND confidence_score<=100)),
 CONSTRAINT chk_ocr_attempt_quality CHECK (quality_json IS NULL OR JSON_VALID(quality_json)),
 CONSTRAINT chk_ocr_attempt_cache CHECK ((cache_hit=0 AND cache_source_attempt_id IS NULL) OR (cache_hit=1 AND cache_source_attempt_id IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE ocr_image_cache (
 image_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 provider VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 feature VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 feature_version VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 canonical_attempt_id BIGINT UNSIGNED NOT NULL,
 hit_count INT UNSIGNED NOT NULL DEFAULT 0,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 last_used_at DATETIME NULL,
 PRIMARY KEY (image_sha256,provider,feature,feature_version),
 KEY idx_ocr_cache_attempt (canonical_attempt_id),
 CONSTRAINT fk_ocr_cache_attempt FOREIGN KEY (canonical_attempt_id) REFERENCES ocr_scan_attempts(attempt_id) ON DELETE CASCADE,
 CONSTRAINT chk_ocr_cache_hash CHECK (image_sha256 REGEXP '^[0-9a-f]{64}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
