<?php
declare(strict_types=1);
require_once __DIR__.'/../modules/payment/includes/ManagedBillingNotificationDispatcher.php';
if(!in_array('sqlite',PDO::getAvailableDrivers(),true)){fwrite(STDERR,"SKIP: PDO SQLite is unavailable.\n");exit(0);}
$pdo=new PDO('sqlite::memory:',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
foreach([
 'CREATE TABLE students (student_id INTEGER PRIMARY KEY,user_id INTEGER)',
 'CREATE TABLE billing (billing_id INTEGER PRIMARY KEY,remaining_balance REAL)',
 'CREATE TABLE billing_run_assignments (assignment_id INTEGER PRIMARY KEY,run_id INTEGER,student_id INTEGER,billing_id INTEGER,notification_state TEXT)',
 'CREATE UNIQUE INDEX uq_assignment ON billing_run_assignments(run_id,student_id)',
 "CREATE TABLE billing_notification_outbox (outbox_id INTEGER PRIMARY KEY AUTOINCREMENT,run_id INTEGER,student_id INTEGER,billing_id INTEGER,event_key TEXT UNIQUE,academic_year TEXT,semester TEXT,new_assessment_amount REAL,term_remaining_balance REAL,delivery_status TEXT DEFAULT 'Pending',attempt_count INTEGER DEFAULT 0,last_error TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,sent_at TEXT)",
 'CREATE UNIQUE INDEX uq_outbox_run_student ON billing_notification_outbox(run_id,student_id)',
 'CREATE TABLE payment_notifications (notification_id INTEGER PRIMARY KEY AUTOINCREMENT,recipient_user_id INTEGER,event_key TEXT,title TEXT,body TEXT,target_url TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,read_at TEXT)',
 'CREATE UNIQUE INDEX uq_payment_notification_event ON payment_notifications(recipient_user_id,event_key)'
] as $sql)$pdo->exec($sql);
$checks=0;function ncheck(bool $ok,string $message):void{global $checks;$checks++;if(!$ok)throw new RuntimeException($message);}
function seedEvent(PDO $pdo,int $run,int $student,int $billing,string $key,string $status='Pending',int $attempts=0,string $updated='2000-01-01 00:00:00'):void{$pdo->prepare('INSERT INTO billing_run_assignments(run_id,student_id,billing_id,notification_state) VALUES(?,?,?,?)')->execute([$run,$student,$billing,$status]);$pdo->prepare('INSERT INTO billing_notification_outbox(run_id,student_id,billing_id,event_key,academic_year,semester,new_assessment_amount,term_remaining_balance,delivery_status,attempt_count,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)')->execute([$run,$student,$billing,$key,'2099-2100','1st',125,875,$status,$attempts,$updated]);}
$pdo->exec("INSERT INTO students VALUES(1,101),(2,102),(3,NULL),(4,104);INSERT INTO billing VALUES(11,875),(12,500),(13,250),(14,100)");
$dispatcher=new ManagedBillingNotificationDispatcher($pdo,2,0,1);
seedEvent($pdo,1,1,11,'managed-run:1:student:1');$before=(float)$pdo->query('SELECT remaining_balance FROM billing WHERE billing_id=11')->fetchColumn();$result=$dispatcher->dispatchDue(1,1);
ncheck($result['sent']===1,'pending event is delivered');ncheck((int)$pdo->query('SELECT COUNT(*) FROM payment_notifications WHERE recipient_user_id=101')->fetchColumn()===1,'correct student user receives one notification');ncheck($pdo->query("SELECT delivery_status FROM billing_notification_outbox WHERE run_id=1")->fetchColumn()==='Sent','outbox records durable delivery');ncheck($pdo->query("SELECT notification_state FROM billing_run_assignments WHERE run_id=1")->fetchColumn()==='Sent','assignment mirrors durable notification creation');ncheck((float)$pdo->query('SELECT remaining_balance FROM billing WHERE billing_id=11')->fetchColumn()===$before,'dispatch does not alter billing balance');
$dispatcher->dispatchDue(1,1);ncheck((int)$pdo->query('SELECT COUNT(*) FROM payment_notifications WHERE recipient_user_id=101')->fetchColumn()===1,'retry does not duplicate a sent event');
seedEvent($pdo,2,2,12,'managed-run:2:student:2');$pdo->prepare("INSERT INTO payment_notifications(recipient_user_id,event_key,title,body,target_url,read_at) VALUES(?,?,?,?,?,'2026-01-01 00:00:00')")->execute([102,'managed-run:2:student:2','Existing','Existing body','/existing']);$dispatcher->dispatchDue(1,2);ncheck((int)$pdo->query("SELECT COUNT(*) FROM payment_notifications WHERE event_key='managed-run:2:student:2'")->fetchColumn()===1,'database uniqueness makes replay idempotent');ncheck($pdo->query("SELECT read_at FROM payment_notifications WHERE event_key='managed-run:2:student:2'")->fetchColumn()==='2026-01-01 00:00:00','existing read state is preserved');
seedEvent($pdo,3,3,13,'managed-run:3:student:3');$dispatcher->dispatchDue(1,3);ncheck($pdo->query('SELECT delivery_status FROM billing_notification_outbox WHERE run_id=3')->fetchColumn()==='PendingAccountLink','missing account remains recoverable');ncheck($pdo->query('SELECT last_error FROM billing_notification_outbox WHERE run_id=3')->fetchColumn()==='RECIPIENT_ACCOUNT_NOT_LINKED','missing account stores safe classification');
seedEvent($pdo,4,4,14,'managed-run:4:student:4','Processing');$dispatcher->dispatchDue(1,4);ncheck($pdo->query('SELECT delivery_status FROM billing_notification_outbox WHERE run_id=4')->fetchColumn()==='Sent','abandoned Processing claim recovers');
seedEvent($pdo,5,1,11,'managed-run:5:student:1');$pdo->exec("CREATE TRIGGER fail_notice BEFORE INSERT ON payment_notifications WHEN NEW.event_key='managed-run:5:student:1' BEGIN SELECT RAISE(ABORT,'injected'); END");$dispatcher->dispatchDue(1,5);ncheck($pdo->query('SELECT delivery_status FROM billing_notification_outbox WHERE run_id=5')->fetchColumn()==='Failed','storage failure remains diagnosable');$dispatcher->dispatchDue(1,5);$dispatcher->dispatchDue(1,5);ncheck((int)$pdo->query('SELECT attempt_count FROM billing_notification_outbox WHERE run_id=5')->fetchColumn()===2,'permanent failure stops at bounded attempts');ncheck((float)$pdo->query('SELECT remaining_balance FROM billing WHERE billing_id=11')->fetchColumn()===$before,'failed retries do not alter billing');
$source=(string)file_get_contents(__DIR__.'/../modules/payment/includes/ManagedBillingNotificationDispatcher.php');$schema=(string)file_get_contents(__DIR__.'/../modules/payment/database/migrations/managed-billing-migration.sql').(string)file_get_contents(__DIR__.'/../modules/payment/database/migrations/add_fee_billing_workflow.sql');$shared=(string)file_get_contents(__DIR__.'/../includes/notifications.php');
ncheck(str_contains($source,'FOR UPDATE')&&str_contains($schema,'uq_billing_notification_outbox_event')&&str_contains($schema,'uq_payment_notification_event'),'row locking and database uniqueness protect concurrent delivery');ncheck(str_contains($shared,'FROM payment_notifications WHERE recipient_user_id = ?')&&str_contains($shared,'read_at = COALESCE(read_at, NOW())'),'shared student UI reads Payment notifications and preserves read state');
$cli=(string)file_get_contents(__DIR__.'/../modules/payment/dispatch-managed-billing-notifications.php');ncheck(str_contains($cli,"PHP_SAPI!=='cli'")&&str_contains($cli,"'historical-before::'"),'recovery worker is CLI-only and historical recovery is explicitly scoped');
echo "Managed billing notification outbox regression passed: $checks checks.\n";
