<?php
declare(strict_types=1);

// Isolated Phase 5 integration regression. Never falls back to a non-_test database.
require_once __DIR__ . '/../modules/payment/includes/ManagedBillingRunService.php';

$dsn = (string)getenv('MANAGED_BILLING_TEST_DSN');
if ($dsn === '' || !preg_match('/dbname=([^;]+)/i', $dsn, $match) || !str_ends_with(strtolower($match[1]), '_test')) {
    fwrite(STDERR, "Refusing to run: MANAGED_BILLING_TEST_DSN must name a MariaDB database ending in _test.\n"); exit(2);
}
putenv('APP_ENV=test'); putenv('PAYMENT_MANAGED_BILLING_DEV_CONTEXT_ENABLED=true');
$pdo = new PDO($dsn, (string)(getenv('MANAGED_BILLING_TEST_USER') ?: 'root'), (string)(getenv('MANAGED_BILLING_TEST_PASS') ?: ''), [PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$database = (string)$pdo->query('SELECT DATABASE()')->fetchColumn();
if (!str_ends_with(strtolower($database), '_test')) { fwrite(STDERR, "Refusing to run: connected database is not a _test database.\n"); exit(2); }
$required = ['billing_runs','billing_run_fee_versions','billing_run_assignments','billing_notification_outbox','payment_notifications','students','fee_groups','fee_types','fees','fee_versions','fee_applicability'];
foreach ($required as $table) { $q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?'); $q->execute([$table]); if (!(int)$q->fetchColumn()) throw new RuntimeException("Missing Phase 5 test table: $table"); }
foreach (['student_number','student_full_name','program_code','year_level','enrollment_status'] as $column) { $q=$pdo->prepare("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='billing_run_assignments' AND column_name=?"); $q->execute([$column]); if (!(int)$q->fetchColumn()) throw new RuntimeException("Missing Phase 5 snapshot column: $column. Apply managed-billing-phase5-migration.sql to this _test database first."); }
foreach (['initiated_by_name_snapshot','approved_by_name_snapshot'] as $column) { $q=$pdo->prepare("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='billing_runs' AND column_name=?"); $q->execute([$column]); if (!(int)$q->fetchColumn()) throw new RuntimeException("Missing Phase 5 approval audit column: $column. Apply managed-billing-run-approval-audit.sql to this _test database first."); }

$checks=0; $ids=['students'=>[],'fees'=>[],'versions'=>[]]; $tag='P5'.bin2hex(random_bytes(5));
function ok5(bool $condition, string $message): void { global $checks; $checks++; if (!$condition) throw new RuntimeException("Assertion failed: $message"); }
function cohort5(array $students): array { return array_map(static fn(array $s): array => ['student_id'=>$s['id'],'student_number'=>$s['number'],'full_name'=>$s['name'],'program_code'=>'BSIT','year_level'=>'1','enrollment_status'=>'Enrolled'], $students); }
try {
    $pdo->prepare("INSERT INTO fee_groups (group_code,group_name,status,sort_order) VALUES (?,?,'Active',999)")->execute(['G'.$tag,'Phase 5 '.$tag]); $ids['group']=(int)$pdo->lastInsertId();
    $pdo->prepare("INSERT INTO fee_types (fee_group_id,type_code,type_name,status,sort_order) VALUES (?, ?,?,'Active',999)")->execute([$ids['group'],'T'.$tag,'Phase 5 '.$tag]); $ids['type']=(int)$pdo->lastInsertId();
    foreach ([1,2] as $n) { $number="P5-$tag-$n"; $pdo->prepare("INSERT INTO students (user_id,student_number,full_name,course,year_level,status) VALUES (?,?,?,?,?,'Enrolled')")->execute([980000000+random_int(1,99999),$number,"Phase 5 Student $n",'Do not read','99']); $ids['students'][]=['id'=>(int)$pdo->lastInsertId(),'number'=>$number,'name'=>"Phase 5 Student $n"]; }
    $pdo->prepare("INSERT INTO fees (fee_code,fee_name,fee_type_id,identity_status,default_amount,is_required,status) VALUES (?,?,?,?,0,0,'Inactive')")->execute(['F'.$tag,'Phase 5 required',$ids['type'],'Active']); $ids['fees'][]=(int)$pdo->lastInsertId();
    $pdo->prepare("INSERT INTO fee_versions (fee_id,version_no,academic_year,semester,amount,behavior,is_required,effective_status) VALUES (?,1,'2097-2098','1st',125,'Standard',1,'Active')")->execute([end($ids['fees'])]); $requiredVersion=(int)$pdo->lastInsertId(); $ids['versions'][]=$requiredVersion;
    $pdo->prepare('INSERT INTO fee_applicability (fee_version_id,course,year_level,applies_to_all_courses,applies_to_all_year_levels) VALUES (?,NULL,NULL,1,1)')->execute([$requiredVersion]);

    $service=new ManagedBillingRunService($pdo); $input=['academic_year'=>'2097-2098','semester'=>'1st','cohort'=>cohort5($ids['students']),'selected_reviewable_fee_version_ids'=>[]];
    $preview=$service->preview($input); ok5($preview['cohort_count']===2 && $preview['projected_amount']===250.0,'controlled cohort preview uses fee snapshots, not student academic columns');
    $draft=$service->createDraft($input,700101,'Phase 5 Officer'); $runId=(int)$draft['run']['run_id']; $ids['runs'][]=$runId;
    ok5($draft['run']['status']==='Draft' && count($draft['assignments'])===2,'Draft snapshots controlled cohort into unique assignments');
    ok5($draft['assignments'][0]['student_full_name']!=='' && $draft['assignments'][0]['program_code']==='BSIT','assignment stores audit/display context snapshot');
    try { $service->approve($runId,700101); throw new RuntimeException('self approval should fail'); } catch (ManagedBillingRunException $e) { ok5($e->errorCode==='SELF_APPROVAL_FORBIDDEN','creator cannot self-approve'); }
    $approved=$service->approve($runId,700102,'Phase 5 Admin'); ok5($approved['run']['status']==='Approved' && $approved['run']['initiated_by_name_snapshot']==='Phase 5 Officer' && $approved['run']['approved_by_name_snapshot']==='Phase 5 Admin','different Accounting Admin actor approves Draft with audit name snapshots');
    try { $service->processChunk($runId,700101,73); throw new RuntimeException('invalid chunk size should fail'); } catch (ManagedBillingRunException $e) { ok5($e->errorCode==='CHUNK_SIZE_INVALID','only 25, 50, 100 chunk sizes are accepted'); }
    $pdo->prepare("UPDATE billing_runs SET runner_token='active-test-runner',lease_expires_at=DATE_ADD(CURRENT_TIMESTAMP,INTERVAL 15 MINUTE) WHERE run_id=?")->execute([$runId]);
    try { $service->processChunk($runId,700101,25); throw new RuntimeException('active lease should block another runner'); } catch (ManagedBillingRunException $e) { ok5($e->errorCode==='RUN_LEASED','active runner lease prevents concurrent chunk processing'); }
    $pdo->prepare('UPDATE billing_runs SET runner_token=NULL,lease_expires_at=NULL WHERE run_id=?')->execute([$runId]);
    $completed=$service->processChunk($runId,700101,25); ok5($completed['run']['status']==='Completed' && (int)$completed['run']['actual_added_student_count']===2,'25-sized chunk invokes Phase 4 per student');
    $outbox=$pdo->prepare('SELECT COUNT(*) FROM billing_notification_outbox WHERE run_id=? AND delivery_status=\'Sent\''); $outbox->execute([$runId]); ok5((int)$outbox->fetchColumn()===2,'one delivered outbox event exists per newly assessed student');
    $notice=$pdo->prepare("SELECT COUNT(*) FROM payment_notifications WHERE event_key LIKE ?");$notice->execute(['managed-run:'.$runId.':student:%']);ok5((int)$notice->fetchColumn()===2,'dispatcher creates one student-facing notification per managed assignment');
    $completedAgain=$service->detail($runId); ok5(count($completedAgain['assignments'])===2 && (int)$completedAgain['run']['actual_added_item_count']===2,'run reconciliation reflects assignment outcomes');
    $other=$service->createDraft($input,700103); $otherId=(int)$other['run']['run_id']; $ids['runs'][]=$otherId; $service->approve($otherId,700104); $repeat=$service->processChunk($otherId,700103,50); ok5($repeat['run']['status']==='Completed' && (int)$repeat['run']['actual_already_assessed_student_count']===2,'retry/re-run cannot create duplicate managed obligations');
    $third=$service->createDraft($input,700105); $thirdId=(int)$third['run']['run_id']; $ids['runs'][]=$thirdId; $service->approve($thirdId,700106); $large=$service->processChunk($thirdId,700105,100); ok5($large['run']['status']==='Completed','100-sized chunk executes safely');
    $crashNumber="P5-$tag-crash"; $pdo->prepare("INSERT INTO students (user_id,student_number,full_name,course,year_level,status) VALUES (?,?,?,?,?,'Enrolled')")->execute([980000000+random_int(1,99999),$crashNumber,'Phase 5 Crash Student','Do not read','99']); $crashStudent=['id'=>(int)$pdo->lastInsertId(),'number'=>$crashNumber,'name'=>'Phase 5 Crash Student']; $ids['students'][]=$crashStudent;
    $crashContext=BillingStudentContext::fromArray(['student_id'=>$crashStudent['id'],'student_number'=>$crashStudent['number'],'full_name'=>$crashStudent['name'],'academic_year'=>'2097-2098','semester'=>'1st','program_code'=>'BSIT','year_level'=>'1','financially_eligible'=>true,'eligibility_source'=>'test','metadata'=>['program_code_canonical'=>true]]);
    $writer=new ManagedStandardAssessmentWriter($pdo,new ManagedStandardAssessmentService($pdo)); $pdo->beginTransaction(); try { $writer->commitStudentAssessment($crashContext,[],700107,false); throw new RuntimeException('simulated interruption before assignment/outbox completion'); } catch (RuntimeException $e) { $pdo->rollBack(); }
    $q=$pdo->prepare('SELECT COUNT(*) FROM managed_assessment_headers WHERE student_id=? AND academic_year=? AND semester=?'); $q->execute([$crashStudent['id'],'2097-2098','1st']); ok5((int)$q->fetchColumn()===0,'caller-owned transaction rolls back financial write before assignment/outbox completion');
    $crashInput=['academic_year'=>'2097-2098','semester'=>'1st','cohort'=>cohort5([$crashStudent]),'selected_reviewable_fee_version_ids'=>[]]; $crashRun=$service->createDraft($crashInput,700107); $crashRunId=(int)$crashRun['run']['run_id']; $ids['runs'][]=$crashRunId; $service->approve($crashRunId,700108); $crashResult=$service->processChunk($crashRunId,700107,25);
    $q=$pdo->prepare('SELECT COUNT(*) FROM billing_items bi JOIN managed_assessment_headers h ON h.billing_id=bi.billing_id WHERE h.student_id=? AND bi.fee_version_id=?'); $q->execute([$crashStudent['id'],$requiredVersion]); $singleItem=(int)$q->fetchColumn(); $q=$pdo->prepare('SELECT COUNT(*) FROM billing_notification_outbox WHERE run_id=? AND student_id=?'); $q->execute([$crashRunId,$crashStudent['id']]); ok5($crashResult['run']['status']==='Completed' && $singleItem===1 && (int)$q->fetchColumn()===1,'interruption retry creates one financial item and exactly one outbox intent');
    echo "Managed Billing Run MariaDB regression passed: $checks checks on $database.\n";
} finally {
    if ($pdo->inTransaction()) $pdo->rollBack();
    foreach (array_reverse($ids['runs'] ?? []) as $runId) { $pdo->prepare('DELETE FROM payment_notifications WHERE event_key LIKE ?')->execute(['managed-run:'.$runId.':student:%']); $pdo->prepare('DELETE FROM billing_notification_outbox WHERE run_id=?')->execute([$runId]); $pdo->prepare('DELETE FROM billing_run_assignments WHERE run_id=?')->execute([$runId]); $pdo->prepare('DELETE FROM billing_run_fee_versions WHERE run_id=?')->execute([$runId]); $pdo->prepare('DELETE FROM billing_runs WHERE run_id=?')->execute([$runId]); }
    $studentIds=array_column($ids['students'] ?? [], 'id'); if ($studentIds) { $marks=implode(',',array_fill(0,count($studentIds),'?')); $pdo->prepare("DELETE bi FROM billing_items bi JOIN billing b ON b.billing_id=bi.billing_id WHERE b.student_id IN ($marks)")->execute($studentIds); $pdo->prepare("DELETE FROM managed_assessment_headers WHERE student_id IN ($marks)")->execute($studentIds); $pdo->prepare("DELETE FROM billing WHERE student_id IN ($marks)")->execute($studentIds); $pdo->prepare("DELETE FROM students WHERE student_id IN ($marks)")->execute($studentIds); }
    foreach ($ids['versions'] ?? [] as $id) $pdo->prepare('DELETE FROM fee_applicability WHERE fee_version_id=?')->execute([$id]); foreach ($ids['versions'] ?? [] as $id) $pdo->prepare('DELETE FROM fee_versions WHERE fee_version_id=?')->execute([$id]); foreach ($ids['fees'] ?? [] as $id) $pdo->prepare('DELETE FROM fees WHERE fee_id=?')->execute([$id]); if(isset($ids['type'])) $pdo->prepare('DELETE FROM fee_types WHERE fee_type_id=?')->execute([$ids['type']]); if(isset($ids['group'])) $pdo->prepare('DELETE FROM fee_groups WHERE fee_group_id=?')->execute([$ids['group']]);
}
