<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')throw new RuntimeException('CLI only');
require_once __DIR__.'/../modules/payment/includes/PaymentAdministrativeAuditService.php';
$checks=0;function acheck(bool $ok,string $message):void{global $checks;$checks++;if(!$ok)throw new RuntimeException($message);}
$pdo=new PDO('sqlite::memory:',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
$pdo->exec('CREATE TABLE users(id INTEGER PRIMARY KEY,full_name TEXT,role_key TEXT,status TEXT)');
$pdo->exec("INSERT INTO users VALUES(1,'MIS Actor','mis_admin','active'),(2,'Cashier Target','cashier','active'),(3,'Student Hidden','student','active')");
$pdo->exec('CREATE TABLE activity_logs(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,user_name TEXT,role_key TEXT,action TEXT,module_key TEXT,entity_type TEXT,entity_id INTEGER,detail TEXT,before_state TEXT,after_state TEXT,correlation_id TEXT,ip_address TEXT,user_agent TEXT,created_at TEXT)');
$insert=$pdo->prepare('INSERT INTO activity_logs(user_id,user_name,role_key,action,module_key,entity_type,entity_id,detail,before_state,after_state,correlation_id,ip_address,user_agent,created_at)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
$cid='11111111-1111-4111-8111-111111111111';
$insert->execute([1,'MIS Actor','mis_admin','PAYMENT_USER_ROLE_CHANGED','payment','payment_user',2,'safe','{"role_key":"cashier","password":"OLD","credentials":{"private_key":"PRIVATE"}}','{"role_key":"accounting_officer","auth":{"token":"TOKEN"},"metadata":{"session_id":"SESSION"},"sessions_revoked":true}',$cid,'127.0.0.1','audit-agent','2026-10-05 10:00:00']);
$insert->execute([1,'MIS Actor','mis_admin','accounting_user_create','payment',null,null,'legacy free text with password=BAD',null,null,null,null,null,'2026-10-04 10:00:00']);
$insert->execute([1,'MIS Actor','mis_admin','PAYMONGO_MODE_CHANGED','payment','paymongo_configuration',null,'safe','{"gateway_mode":"test","webhook_secret":"WEBHOOK"}','{"gateway_mode":"live","api_key":"APIKEY"}','22222222-2222-4222-8222-222222222222','10.0.0.1','provider-agent','2026-10-03 10:00:00']);
$insert->execute([1,'MIS Actor','mis_admin','OCR_CONFIGURATION_UPDATED','payment','ocr_configuration',null,'safe','{"enabled":false,"google_credential_path":"/secret/path"}','{"enabled":true,"project_id":"safe-project"}','33333333-3333-4333-8333-333333333333',null,null,'2026-10-02 10:00:00']);
$insert->execute([1,'MIS Actor','mis_admin','RECEIPT_OCR_EVIDENCE_RECORDED','payment','payment_concern',77,'private evidence',null,'{"success":true,"attempt_number":1,"ocr_text":"CARD 123","amount":"999.00","reference":"BANK-SECRET","receipt_path":"/private/receipt"}','44444444-4444-4444-8444-444444444444',null,null,'2026-10-01 10:00:00']);
$insert->execute([1,'MIS Actor','mis_admin','PAYMENT_USER_UPDATED','payment','payment_user',999,'deleted target','{"full_name":"Old"}','{"full_name":"New"}','55555555-5555-4555-8555-555555555555',null,null,'2026-09-30 10:00:00']);
$insert->execute([3,'Student Hidden','student','process_walk_in_payment','payment','payment',9,'financial',null,'{"amount":500}',null,null,null,'2026-10-05 09:00:00']);
$insert->execute([1,'MIS Actor','mis_admin','global_user_delete','System','user',2,'global',null,null,null,null,null,'2026-10-05 08:00:00']);
$clock=new DateTimeImmutable('2026-10-05 12:00:00',new DateTimeZone('Asia/Manila'));$service=new PaymentAdministrativeAuditService($pdo,$clock);
$events=$service->events([]);acheck($events['total']===6,'Only approved Payment administrative events visible');acheck($events['page_size']===25&&$events['page']===1,'Default bounded pagination');
$names=array_column($events['items'],'event');acheck(in_array('PAYMENT_USER_ROLE_CHANGED',$names,true),'Canonical user event visible');acheck(in_array('PAYMENT_USER_CREATED',$names,true),'Legacy user event normalized');acheck(in_array('PAYMONGO_MODE_CHANGED',$names,true),'PayMongo event visible');acheck(in_array('OCR_CONFIGURATION_UPDATED',$names,true),'OCR configuration visible');acheck(!str_contains(json_encode($events),'process_walk_in_payment'),'Student financial event hidden');acheck(!str_contains(json_encode($events),'global_user_delete'),'Global event hidden');acheck(!str_contains(json_encode($events),'legacy free text'),'Legacy detail not returned');
$detail=$service->detail(1);acheck($detail['actor']['id']===1&&$detail['actor']['name']==='MIS Actor'&&$detail['actor']['role']==='mis_admin','Actor snapshot resolved');acheck($detail['target']['label']==='Cashier Target','Current managed target resolved');acheck($detail['change']['before']['role_key']==='cashier'&&$detail['change']['after']['role_key']==='accounting_officer','Before and after state available');acheck(count($detail['change']['fields'])>=2,'Changed fields prepared');acheck($detail['request_context']['ip_address']==='127.0.0.1'&&$detail['request_context']['user_agent']==='audit-agent','Protected request context available');acheck($detail['request_context']['correlation_id']===$cid,'Correlation returned');
$encoded=json_encode($detail,JSON_THROW_ON_ERROR);foreach(['OLD','PRIVATE','TOKEN','SESSION']as$secret)acheck(!str_contains($encoded,$secret),'Nested secret redacted: '.$secret);acheck(str_contains($encoded,'[REDACTED]'),'Redaction marker used');acheck(str_contains($encoded,'sessions_revoked'),'Safe session revocation evidence preserved');
$deleted=$service->detail(6);acheck($deleted['target']['label']==='Payment user #999','Deleted target uses neutral fallback');
$ocr=$service->detail(5);$ocrJson=json_encode($ocr,JSON_THROW_ON_ERROR);acheck(str_contains($ocrJson,'attempt_number')&&str_contains($ocrJson,'success'),'Safe OCR technical state visible');foreach(['CARD 123','999.00','BANK-SECRET','/private/receipt','ocr_text','amount','reference','receipt_path']as$private)acheck(!str_contains($ocrJson,$private),'OCR private evidence excluded: '.$private);
$related=$service->correlation($cid);acheck($related['total']===1&&$related['items'][0]['id']===1,'Correlation view returns approved event');
$summary=$service->summary();acheck($summary['events_today']===1,'Today summary reliable');acheck($summary['user_administration']===2,'User administration summary');acheck($summary['integration_administration']===3,'Integration summary');acheck($summary['security_administration']===1,'Security summary');
acheck($service->events(['category'=>'INTEGRATION_PAYMONGO'])['total']===1,'Category filter');acheck($service->events(['event'=>'PAYMENT_USER_CREATED'])['total']===1,'Canonical event filter includes legacy alias');acheck($service->events(['actor'=>1])['total']===6,'Actor filter');acheck($service->events(['target'=>2])['total']===1,'Target filter');acheck($service->events(['result'=>'PARTIAL'])['total']===0,'Result filter');acheck($service->events(['correlation_id'=>$cid])['total']===1,'Correlation filter');acheck($service->events(['date_from'=>'2026-10-03','date_to'=>'2026-10-05'])['total']===3,'Date range filter');foreach([25,50,100]as$size)acheck($service->events(['page_size'=>$size])['page_size']===$size,'Allowed page size '.$size);
foreach([['page_size'=>101],['page_size'=>1],['date_from'=>'bad'],['date_from'=>'2026-10-05','date_to'=>'2026-10-01'],['category'=>'FINANCIAL'],['event'=>'process_walk_in_payment'],['actor'=>'1 OR 1=1'],['target'=>-1],['result'=>'BREACH'],['correlation_id'=>'x OR 1=1']]as$bad){try{$service->events($bad);acheck(false,'Unsafe filter accepted');}catch(InvalidArgumentException){acheck(true,'Unsafe filter rejected');}}
try{$service->correlation('not-a-uuid');acheck(false,'Invalid correlation accepted');}catch(InvalidArgumentException){acheck(true,'Invalid correlation rejected');}
$root=dirname(__DIR__);$auth=file_get_contents($root.'/includes/authentication.php');$config=file_get_contents($root.'/config/config.php');$api=file_get_contents($root.'/modules/payment/api/mis_admin/administrative-audit.php');$page=file_get_contents($root.'/modules/payment/pages/mis_admin/administrative-audit.php');$client=file_get_contents($root.'/modules/payment/assets/js/payment-administrative-audit.js');$mis6page=file_get_contents($root.'/modules/payment/pages/mis_admin/security-monitoring.php');$mis6js=file_get_contents($root.'/modules/payment/assets/js/payment-security-monitoring.js');$overview=file_get_contents($root.'/modules/payment/pages/mis_admin/dashboard.php');
acheck(str_contains($auth,"'payment.audit.view'"),'MIS audit permission registered');foreach(['accounting_admin','accounting_officer','cashier']as$role){$start=strpos($auth,"'{$role}' => [");$end=strpos($auth,'],',$start);acheck(!str_contains(substr($auth,$start,$end-$start),'payment.audit.view'),$role.' denied audit permission');}acheck(str_contains($config,"'mis_admin/administrative-audit'")&&str_contains($config,"'permission' => 'payment.audit.view'"),'Permission-filtered navigation');acheck(str_contains($page,"requirePaymentPermission('payment.audit.view')"),'Page requires exact permission');acheck(str_contains($api,"requirePaymentPermission('payment.audit.view')")&&str_contains($api,"'AUTHENTICATION_REQUIRED'")&&str_contains($api,"actorRow['status']!=='active'"),'API enforces auth, permission, and active actor');acheck(!preg_match('/\b(INSERT|UPDATE|DELETE|TRUNCATE)\b/i',$api),'Audit API has no mutation SQL');acheck(!preg_match('/Clear Logs|Delete Audit|Purge Logs|Resolve Event/i',$page.$client),'No audit mutation UI');acheck(str_contains($overview,'View Administrative Audit'),'MIS Overview drill-down');acheck(str_contains($mis6page,'data-audit-url')&&str_contains($mis6js,'event_id'),'MIS-6 audit cross-link');
echo "PASS: {$checks} MIS-7 administrative audit checks.\n";
