<?php

declare(strict_types=1);

// Destructive fixture writes are permitted only on two explicitly configured *_test databases.
define('ROOT_PATH', dirname(__DIR__));
require_once ROOT_PATH . '/modules/payment/includes/SchoolSalesCatalogService.php';

function isolatedConfig(string $name): ?array
{
    $dsn=(string)getenv($name);
    if($dsn==='' || !preg_match('/dbname=([^;]+)/i',$dsn,$m) || !str_ends_with(strtolower($m[1]),'_test')) return null;
    $prefix=str_replace('_DSN','',$name);
    return [$dsn,(string)(getenv($prefix.'_USER')?:'root'),(string)(getenv($prefix.'_PASS')?:''),$m[1]];
}
$paymentConfig=isolatedConfig('SCHOOL_SALES_CATALOG_TEST_DSN');
$coreConfig=isolatedConfig('SCHOOL_SALES_CATALOG_CORE_TEST_DSN');
if($paymentConfig===null||$coreConfig===null){echo "NOT RUN: isolated School Sales Catalog Payment/Core *_test DSNs are not configured. No database write was attempted.\n";exit(0);}
[$paymentDsn,$paymentUser,$paymentPass]=$paymentConfig;[$coreDsn,$coreUser,$corePass]=$coreConfig;
$payment=new PDO($paymentDsn,$paymentUser,$paymentPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
$core=new PDO($coreDsn,$coreUser,$corePass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
$paymentDb=(string)$payment->query('SELECT DATABASE()')->fetchColumn();$coreDb=(string)$core->query('SELECT DATABASE()')->fetchColumn();
if(!str_ends_with(strtolower($paymentDb),'_test')||!str_ends_with(strtolower($coreDb),'_test')){fwrite(STDERR,"REFUSED: connected database is not isolated *_test.\n");exit(2);}
$required=['school_sale_categories','school_sale_item_types','school_sale_items','school_sale_item_variants','school_sale_variant_prices','school_sale_item_applicability','school_sale_book_details','payment_audit_outbox'];
foreach($required as $table){$q=$payment->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?');$q->execute([$table]);if(!(int)$q->fetchColumn())throw new RuntimeException("Missing isolated test table: $table");}
$q=$core->prepare("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='activity_logs'");$q->execute();if(!(int)$q->fetchColumn())throw new RuntimeException('Missing isolated Core test activity_logs table.');

final class CatalogIntegrationScopeProvider implements SchoolSalesApplicabilityScopeProvider {public function isCanonicalProgram(string $v):bool{return $v==='BSIT';}public function isCanonicalYearLevel(string $v):bool{return in_array($v,['1','2','3','4'],true);}public function isCanonicalProgramYear(string $p,string $y):bool{return $p==='BSIT'&&$this->isCanonicalYearLevel($y);}}
$checks=0;$tag='C'.strtoupper(bin2hex(random_bytes(5)));$ids=['items'=>[],'categories'=>[],'types'=>[]];
function ccheck(bool $ok,string $message):void{global $checks;$checks++;if(!$ok)throw new RuntimeException("Assertion failed: $message");}
function cid():string{return CatalogCorrelationId::generate();}
function actor():array{return ['user_id'=>990001,'user_name'=>'Catalog Integration','role_key'=>'accounting_admin','permissions'=>['school_sales.catalog.manage','school_sales.catalog.activate'],'ip_address'=>'127.0.0.1','user_agent'=>'MariaDB integration'];}
function runRace(string $action,array $left,array $right):array{$worker=__DIR__.'/helpers/payment-school-sales-concurrency-worker.php';$start=microtime(true)+.35;$processes=[];foreach([$left,$right]as$p){$cmd=[PHP_BINARY,$worker,$action,base64_encode(json_encode($p,JSON_THROW_ON_ERROR)),(string)$start];$proc=proc_open($cmd,[1=>['pipe','w'],2=>['pipe','w']],$pipes,null,null,['bypass_shell'=>true]);if(!is_resource($proc))throw new RuntimeException('Unable to start concurrency worker.');$processes[]=['proc'=>$proc,'pipes'=>$pipes];}$results=[];foreach($processes as$entry){$raw=stream_get_contents($entry['pipes'][1]);$err=stream_get_contents($entry['pipes'][2]);fclose($entry['pipes'][1]);fclose($entry['pipes'][2]);$exit=proc_close($entry['proc']);if($exit!==0)throw new RuntimeException("Concurrency worker failed: $err");$results[]=json_decode($raw,true,512,JSON_THROW_ON_ERROR);}return$results;}
function oneSuccess(array $race):bool{return count(array_filter($race,fn($r)=>$r['ok']))===1;}
function service(PDO $p,?PDO $c):SchoolSalesCatalogService{$writer=$c?new StructuredActivityAuditWriter($c):null;return new SchoolSalesCatalogService($p,new SchoolSalesCatalogMutationInfrastructure($p,new PaymentAuditOutboxService($p,$writer)),new CatalogIntegrationScopeProvider());}
function itemData(string $code,int $category,int $type,string $mode='ALL'):array{return ['item_code'=>$code,'item_name'=>$code,'sale_category_id'=>$category,'sale_item_type_id'=>$type,'description'=>'Concurrency fixture','applicability_mode'=>$mode];}
function priceData(string $from,?string $to=null,string $amount='100.00'):array{return ['amount'=>$amount,'currency'=>'PHP','effective_from'=>$from,'effective_to'=>$to];}
function readyVariantFixture(SchoolSalesCatalogService $svc,PDO $pdo,array &$ids,string $code,int $category,int $type):array{$item=$svc->createDraftItem(cid(),itemData($code,$category,$type),actor())['result'];$itemId=(int)$item['sale_item_id'];$ids['items'][]=$itemId;$variant=$svc->createStandardDraftVariant($itemId,cid(),actor(),['sku'=>$code.'-SKU'])['result'];$variantId=(int)$variant['sale_variant_id'];$pdo->prepare("UPDATE school_sale_item_variants SET status='Active' WHERE sale_variant_id=?")->execute([$variantId]);$price=$svc->createDraftVariantPrice($variantId,cid(),priceData('2020-01-01 00:00:00'),actor())['result'];$svc->activateVariantPrice((int)$price['sale_variant_price_id'],cid(),actor());return[$itemId,$variantId,(int)$price['sale_variant_price_id']];}

try{
 $payment->prepare("INSERT INTO school_sale_categories(category_code,category_name,sort_order,status)VALUES(?, ?,999,'Active')")->execute([$tag,'Test '.$tag]);$category=(int)$payment->lastInsertId();$ids['categories'][]=$category;
 $uniform=(int)$payment->query("SELECT sale_item_type_id FROM school_sale_item_types WHERE type_code='UNIFORM' AND status='Active'")->fetchColumn();$book=(int)$payment->query("SELECT sale_item_type_id FROM school_sale_item_types WHERE type_code='BOOK' AND status='Active'")->fetchColumn();if(!$uniform||!$book)throw new RuntimeException('Isolated test DB requires active UNIFORM and BOOK controlled types.');
 $svc=service($payment,$core);

 // Correlation idempotency under real concurrent connections.
 $same=cid();$payload=['correlation_id'=>$same,'data'=>itemData($tag.'-IDEMP',$category,$uniform)];$race=runRace('create_item',$payload,$payload);ccheck(count(array_filter($race,fn($r)=>$r['ok']))===2,'same correlation/payload returns commit plus replay');$itemId=(int)$payment->query("SELECT sale_item_id FROM school_sale_items WHERE item_code='{$tag}-IDEMP'")->fetchColumn();$ids['items'][]=$itemId;ccheck((int)$payment->query("SELECT COUNT(*) FROM school_sale_items WHERE item_code='{$tag}-IDEMP'")->fetchColumn()===1,'idempotent race creates one item');ccheck((int)$payment->query("SELECT COUNT(*) FROM payment_audit_outbox WHERE correlation_id='{$same}'")->fetchColumn()===1,'idempotent race creates one outbox row');
 $different=cid();$race=runRace('create_item',['correlation_id'=>$different,'data'=>itemData($tag.'-LEFT',$category,$uniform)],['correlation_id'=>$different,'data'=>itemData($tag.'-RIGHT',$category,$uniform)]);ccheck(oneSuccess($race)&&in_array('CORRELATION_ID_CONFLICT',array_column($race,'error'),true),'same correlation with different request conflicts');$winner=$payment->query("SELECT sale_item_id FROM school_sale_items WHERE item_code IN ('{$tag}-LEFT','{$tag}-RIGHT')")->fetchAll(PDO::FETCH_COLUMN);$ids['items']=array_merge($ids['items'],array_map('intval',$winner));ccheck(count($winner)===1,'correlation conflict leaves one business mutation');

 // Database uniqueness races.
 $code=$tag.'-UNIQ';$race=runRace('create_item',['correlation_id'=>cid(),'data'=>itemData($code,$category,$uniform)],['correlation_id'=>cid(),'data'=>itemData($code,$category,$uniform)]);ccheck(oneSuccess($race),'item-code uniqueness race commits once');$uniqueItem=(int)$payment->query("SELECT sale_item_id FROM school_sale_items WHERE item_code='$code'")->fetchColumn();$ids['items'][]=$uniqueItem;
 $race=runRace('create_variant',['correlation_id'=>cid(),'item_id'=>$uniqueItem,'data'=>['variant_code'=>'RACE','variant_name'=>'Race','sku'=>$tag.'-SKU-A','size_label'=>null,'variant_metadata'=>null,'sort_order'=>1]],['correlation_id'=>cid(),'item_id'=>$uniqueItem,'data'=>['variant_code'=>'RACE','variant_name'=>'Race 2','sku'=>$tag.'-SKU-B','size_label'=>null,'variant_metadata'=>null,'sort_order'=>2]]);ccheck(oneSuccess($race),'item-scoped variant-code race commits once');
 $race=runRace('create_variant',['correlation_id'=>cid(),'item_id'=>$uniqueItem,'data'=>['variant_code'=>'SKU1','variant_name'=>'SKU 1','sku'=>$tag.'-GLOBAL','size_label'=>null,'variant_metadata'=>null,'sort_order'=>3]],['correlation_id'=>cid(),'item_id'=>$itemId,'data'=>['variant_code'=>'SKU2','variant_name'=>'SKU 2','sku'=>$tag.'-GLOBAL','size_label'=>null,'variant_metadata'=>null,'sort_order'=>4]]);ccheck(oneSuccess($race),'global SKU race commits once');
 $scopeItem=$svc->createDraftItem(cid(),itemData($tag.'-SCOPE',$category,$uniform,'RESTRICTED'),actor())['result'];$scopeItemId=(int)$scopeItem['sale_item_id'];$ids['items'][]=$scopeItemId;$race=runRace('add_scope',['correlation_id'=>cid(),'item_id'=>$scopeItemId,'data'=>['program_code'=>'BSIT','year_level'=>'1']],['correlation_id'=>cid(),'item_id'=>$scopeItemId,'data'=>['program_code'=>'BSIT','year_level'=>'1']]);ccheck(oneSuccess($race),'Active applicability scope race commits once');

 $priceItem=$svc->createDraftItem(cid(),itemData($tag.'-PRICE',$category,$uniform),actor())['result'];$priceItemId=(int)$priceItem['sale_item_id'];$ids['items'][]=$priceItemId;$variant=$svc->createDraftVariant($priceItemId,cid(),['variant_code'=>'STANDARD','variant_name'=>'Standard','sku'=>$tag.'-PRICE-SKU','size_label'=>null,'variant_metadata'=>null,'sort_order'=>1],actor())['result'];$variantId=(int)$variant['sale_variant_id'];
 $race=runRace('create_price',['correlation_id'=>cid(),'variant_id'=>$variantId,'data'=>priceData('2030-01-01 00:00:00')],['correlation_id'=>cid(),'variant_id'=>$variantId,'data'=>priceData('2030-01-01 00:00:00','2031-01-01 00:00:00','120.00')]);ccheck(oneSuccess($race),'variant/effective-start race commits once');
 $p1=$svc->createDraftVariantPrice($variantId,cid(),priceData('2020-01-01 00:00:00','2040-01-01 00:00:00'),actor())['result'];$p2=$svc->createDraftVariantPrice($variantId,cid(),priceData('2035-01-01 00:00:00','2045-01-01 00:00:00','150.00'),actor())['result'];$race=runRace('activate_price',['correlation_id'=>cid(),'price_id'=>$p1['sale_variant_price_id']],['correlation_id'=>cid(),'price_id'=>$p2['sale_variant_price_id']]);ccheck(oneSuccess($race),'overlapping Active price activations cannot both commit');
 $activeWindows=(int)$payment->query("SELECT COUNT(*) FROM school_sale_variant_prices a JOIN school_sale_variant_prices b ON a.sale_variant_id=b.sale_variant_id AND a.sale_variant_price_id<b.sale_variant_price_id AND a.status='Active' AND b.status='Active' AND (a.effective_to IS NULL OR a.effective_to>b.effective_from) AND (b.effective_to IS NULL OR b.effective_to>a.effective_from) WHERE a.sale_variant_id=$variantId")->fetchColumn();ccheck($activeWindows===0,'no overlapping Active windows remain');

 [$successorItem,$successorVariant,$basePrice]=readyVariantFixture($svc,$payment,$ids,$tag.'-SUCCESSOR',$category,$uniform);$race=runRace('replace_price',['correlation_id'=>cid(),'variant_id'=>$successorVariant,'data'=>priceData('2030-01-01 00:00:00',null,'200.00')],['correlation_id'=>cid(),'variant_id'=>$successorVariant,'data'=>priceData('2031-01-01 00:00:00',null,'210.00')]);ccheck(oneSuccess($race),'simultaneous successor prices cannot both commit');
 [$replaceItem,$replaceVariant,$replaceBase]=readyVariantFixture($svc,$payment,$ids,$tag.'-REPLACE-RETIRE',$category,$uniform);$race=runRace('replace_price',['correlation_id'=>cid(),'variant_id'=>$replaceVariant,'data'=>priceData('2032-01-01 00:00:00',null,'220.00')],['correlation_id'=>cid(),'price_id'=>$replaceBase,'effective_to'=>'2032-01-01 00:00:00']);ccheck(oneSuccess($race),'replacement versus retirement has one coherent winner');
 [$activationItem,$activationVariant,$activationPrice]=readyVariantFixture($svc,$payment,$ids,$tag.'-ACT-RACE',$category,$uniform);$race=runRace('activate_item',['correlation_id'=>cid(),'item_id'=>$activationItem],['correlation_id'=>cid(),'variant_id'=>$activationVariant]);ccheck(oneSuccess($race),'activation versus final variant removal cannot both commit');$status=$payment->query("SELECT status FROM school_sale_items WHERE sale_item_id=$activationItem")->fetchColumn();if($status==='Active')ccheck($svc->evaluateItemActivationReadiness($activationItem)['ready'],'activation race leaves valid Active state');
 [$restrictedItem,$restrictedVariant,$restrictedPrice]=readyVariantFixture($svc,$payment,$ids,$tag.'-ACT-SCOPE',$category,$uniform);$svc->changeItemApplicabilityMode($restrictedItem,'RESTRICTED',cid(),actor());$svc->addItemApplicabilityAssignment($restrictedItem,cid(),['program_code'=>'BSIT','year_level'=>'1'],actor());$race=runRace('activate_item',['correlation_id'=>cid(),'item_id'=>$restrictedItem],['correlation_id'=>cid(),'item_id'=>$restrictedItem,'scopes'=>[['program_code'=>'BSIT','year_level'=>'2']]]);ccheck(count(array_filter($race,fn($r)=>$r['ok']))>=1,'activation versus applicability replacement serializes');$status=$payment->query("SELECT status FROM school_sale_items WHERE sale_item_id=$restrictedItem")->fetchColumn();if($status==='Active'){$activeScope=(int)$payment->query("SELECT sale_item_applicability_id FROM school_sale_item_applicability WHERE sale_item_id=$restrictedItem AND status='Active' LIMIT 1")->fetchColumn();try{$svc->deactivateItemApplicabilityAssignment($activeScope,cid(),actor());throw new RuntimeException('final scope removal should fail');}catch(SchoolSalesCatalogValidationException $e){ccheck($e->getMessage()==='ACTIVE_RESTRICTED_ITEM_REQUIRES_ASSIGNMENT','final RESTRICTED scope cannot be removed');}}

 // Complete BOOK workflow through service; test-only promotion supplies the already-approved Active variant state.
 $bookItem=$svc->createDraftItem(cid(),itemData($tag.'-BOOK',$category,$book),actor())['result'];$bookItemId=(int)$bookItem['sale_item_id'];$ids['items'][]=$bookItemId;$bookVariant=$svc->createStandardDraftVariant($bookItemId,cid(),actor())['result'];$bookVariantId=(int)$bookVariant['sale_variant_id'];$payment->prepare("UPDATE school_sale_item_variants SET status='Active' WHERE sale_variant_id=?")->execute([$bookVariantId]);$bookPrice=$svc->createDraftVariantPrice($bookVariantId,cid(),priceData('2020-01-01 00:00:00'),actor())['result'];$svc->activateVariantPrice((int)$bookPrice['sale_variant_price_id'],cid(),actor());$svc->createBookDetails($bookItemId,cid(),['book_title'=>'Integration Book','author'=>'Test Author','publisher'=>null,'edition'=>null,'isbn'=>'978-1-234567-89-7','notes'=>null],actor());$ready=$svc->evaluateItemActivationReadiness($bookItemId);ccheck($ready['ready'],'fully configured BOOK is activation-ready');$svc->activateItem($bookItemId,cid(),actor());ccheck($svc->evaluateItemActivationReadiness($bookItemId)['ready'],'activated BOOK preserves invariants');
 try{$svc->deactivateVariant($bookVariantId,cid(),actor());throw new RuntimeException('final Active variant removal should fail');}catch(SchoolSalesCatalogValidationException $e){ccheck(str_starts_with($e->getMessage(),'ACTIVE_ITEM_INVARIANT_VIOLATION'),'final Active variant cannot be removed');}
 try{$svc->retireActiveVariantPrice((int)$bookPrice['sale_variant_price_id'],gmdate('Y-m-d H:i:s',time()+60),cid(),actor());throw new RuntimeException('only current price removal should fail');}catch(SchoolSalesCatalogValidationException $e){ccheck($e->getMessage()==='ACTIVE_VARIANT_REQUIRES_REPLACEMENT_PRICE','only current official price cannot be removed');}
 try{$svc->updateBookDetails($bookItemId,cid(),['book_title'=>'Changed'],actor());throw new RuntimeException('Active BOOK edit should fail');}catch(SchoolSalesCatalogValidationException $e){ccheck($e->getMessage()==='ACTIVE_BOOK_DETAILS_IMMUTABLE','Active BOOK metadata protection remains enforced');}
 $svc->deactivateItem($bookItemId,cid(),actor());$svc->archiveItem($bookItemId,cid(),actor());ccheck($payment->query("SELECT status FROM school_sale_items WHERE sale_item_id=$bookItemId")->fetchColumn()==='Archived','end-to-end lifecycle reaches Archived');
 [$bookRaceItem,$bookRaceVariant,$bookRacePrice]=readyVariantFixture($svc,$payment,$ids,$tag.'-BOOK-RACE',$category,$book);$svc->createBookDetails($bookRaceItem,cid(),['book_title'=>'Race Book','author'=>null,'publisher'=>null,'edition'=>null,'isbn'=>null,'notes'=>null],actor());$race=runRace('activate_item',['correlation_id'=>cid(),'item_id'=>$bookRaceItem],['correlation_id'=>cid(),'item_id'=>$bookRaceItem,'data'=>['book_title'=>'Race Book Updated','author'=>null,'publisher'=>null,'edition'=>null,'isbn'=>null,'notes'=>null]]);ccheck(count(array_filter($race,fn($r)=>$r['ok']))>=1,'BOOK activation versus metadata update serializes');$status=$payment->query("SELECT status FROM school_sale_items WHERE sale_item_id=$bookRaceItem")->fetchColumn();if($status==='Active')ccheck($svc->evaluateItemActivationReadiness($bookRaceItem)['ready'],'BOOK activation race leaves valid Active state');

 // Outbox: committed state survives unavailable Core and later reconciles once.
 $pendingSvc=service($payment,null);$pending=$pendingSvc->createDraftItem(cid(),itemData($tag.'-PENDING',$category,$uniform),actor());$pendingItem=(int)$pending['result']['sale_item_id'];$ids['items'][]=$pendingItem;ccheck($pending['committed']&&$pending['audit_status']==='pending','Payment commit survives unavailable Core');$outbox=new PaymentAuditOutboxService($payment,new StructuredActivityAuditWriter($core));$outbox->reconcileDue();$row=$outbox->find($pending['correlation_id']);ccheck($row['delivery_status']==='Delivered','pending outbox later reconciles');$outbox->deliver($pending['correlation_id']);$q=$core->prepare('SELECT COUNT(*) FROM activity_logs WHERE correlation_id=?');$q->execute([$pending['correlation_id']]);ccheck((int)$q->fetchColumn()===1,'repeat delivery creates no duplicate Core correlation');$payment->prepare("UPDATE payment_audit_outbox SET delivery_status='Processing',last_attempt_at='2000-01-01 00:00:00' WHERE correlation_id=?")->execute([$pending['correlation_id']]);$outbox->reconcileDue(100,1);ccheck($outbox->find($pending['correlation_id'])['delivery_status']==='Delivered','stale Processing event recovers');

 $lockCorrelation=cid();$payment->beginTransaction();$lock=$payment->prepare('SELECT sale_item_id FROM school_sale_items WHERE sale_item_id=? FOR UPDATE');$lock->execute([$pendingItem]);$worker=__DIR__.'/helpers/payment-school-sales-concurrency-worker.php';$payload=['correlation_id'=>$lockCorrelation,'item_id'=>$pendingItem];$proc=proc_open([PHP_BINARY,$worker,'activate_item',base64_encode(json_encode($payload,JSON_THROW_ON_ERROR)),(string)microtime(true)],[1=>['pipe','w'],2=>['pipe','w']],$pipes,null,null,['bypass_shell'=>true]);if(!is_resource($proc))throw new RuntimeException('Unable to start lock-timeout worker.');sleep(2);$payment->rollBack();$raw=stream_get_contents($pipes[1]);$stderr=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);if(proc_close($proc)!==0)throw new RuntimeException("Lock-timeout worker failed: $stderr");$lockResult=json_decode($raw,true,512,JSON_THROW_ON_ERROR);ccheck(!$lockResult['ok']&&$lockResult['error']==='CATALOG_CONCURRENCY_CONFLICT','lock timeout maps to a safe conflict code');$q=$payment->prepare('SELECT COUNT(*) FROM payment_audit_outbox WHERE correlation_id=?');$q->execute([$lockCorrelation]);ccheck((int)$q->fetchColumn()===0,'lock timeout leaves no partial or orphan outbox state');

 // Every committed Active fixture must still satisfy authoritative readiness.
 foreach($ids['items'] as$id){$status=$payment->query("SELECT status FROM school_sale_items WHERE sale_item_id=".(int)$id)->fetchColumn();if($status==='Active')ccheck($svc->evaluateItemActivationReadiness((int)$id)['ready'],"Active item $id retains all invariants");}
 echo "PASS: $checks School Sales MariaDB integration/concurrency checks on $paymentDb + $coreDb. No production database was used.\n";
}finally{
 if($payment->inTransaction())$payment->rollBack();
 $payment->exec('DELETE FROM payment_audit_outbox WHERE actor_user_id=990001');
 $core->exec('DELETE FROM activity_logs WHERE user_id=990001');
 if($ids['items']){$marks=implode(',',array_fill(0,count($ids['items']),'?'));$payment->prepare("DELETE FROM payment_audit_outbox WHERE entity_id IN ($marks) AND entity_type LIKE 'school_sale_%'")->execute($ids['items']);$payment->prepare("DELETE FROM school_sale_book_details WHERE sale_item_id IN ($marks)")->execute($ids['items']);$payment->prepare("DELETE FROM school_sale_item_applicability WHERE sale_item_id IN ($marks)")->execute($ids['items']);$payment->prepare("DELETE p FROM school_sale_variant_prices p JOIN school_sale_item_variants v ON v.sale_variant_id=p.sale_variant_id WHERE v.sale_item_id IN ($marks)")->execute($ids['items']);$payment->prepare("DELETE FROM school_sale_item_variants WHERE sale_item_id IN ($marks)")->execute($ids['items']);$payment->prepare("DELETE FROM school_sale_items WHERE sale_item_id IN ($marks)")->execute($ids['items']);}
 foreach($ids['categories'] as$id)$payment->prepare('DELETE FROM school_sale_categories WHERE sale_category_id=?')->execute([$id]);
}
