<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')throw new RuntimeException('CLI only');
require_once __DIR__.'/../config/config.php';
require_once ROOT_PATH.'/includes/authentication.php';
require_once ROOT_PATH.'/modules/payment/includes/PaymentPermissionMatrixService.php';
$n=0;function gcheck(bool$v,string$m):void{global$n;$n++;if(!$v)throw new RuntimeException($m);}function findRow(array$rows,string$role,string$permission):array{foreach($rows as$r)if($r['role']===$role&&$r['permission']===$permission)return$r;throw new RuntimeException("Missing $role $permission");}
$p=new PDO('sqlite::memory:',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$p->exec('CREATE TABLE role_permissions(role_key TEXT,module_key TEXT,granted INTEGER)');$q=$p->prepare('INSERT INTO role_permissions VALUES(?,?,?)');$q->execute(['accounting_officer','billing.individual.process',1]);$q->execute(['cashier','billing.bulk.process',1]);$q->execute(['mis_admin','integration.ocr.manage',0]);$q->execute(['accounting_officer','payment.reconciliation.view',1]);
$data=(new PaymentPermissionMatrixService($p))->load();gcheck($data['authorization_available']===true,'Core should be available');gcheck(count($data['roles'])===4,'Four configurable staff roles required');gcheck(!in_array('student',array_column($data['roles'],'key'),true),'Student excluded');
$r=findRow($data['rows'],'accounting_officer','billing.individual.process');gcheck($r['role_ceiling']==='permitted'&&$r['core_permission']==='granted'&&$r['effective_access']==='allowed','Ceiling plus grant');
$r=findRow($data['rows'],'cashier','billing.bulk.process');gcheck($r['role_ceiling']==='denied'&&$r['core_permission']==='granted'&&$r['effective_access']==='denied'&&$r['editable']===false,'Ceiling blocks and protects');
$r=findRow($data['rows'],'mis_admin','integration.ocr.manage');gcheck($r['core_permission']==='revoked'&&$r['effective_access']==='denied','Explicit revocation');
$r=findRow($data['rows'],'mis_admin','integration.paymongo.manage');gcheck($r['core_permission']==='absent'&&$r['effective_access']==='allowed','Compatibility fallback');
$r=findRow($data['rows'],'mis_admin','payment.permissions.manage');gcheck($r['protected']===true&&$r['editable']===false,'Management permission protected');
$r=findRow($data['rows'],'accounting_officer','payment.reconciliation.process');gcheck($r['core_permission']==='absent'&&$r['effective_access']==='denied','Reconciliation requires explicit grant');
gcheck(paymentCanonicalPermission('payment.concern_review')==='payment.concern.view'&&paymentRoleAllowsPermission('accounting_officer','payment.concern_review'),'Canonical alias');
$p->exec('DROP TABLE role_permissions');$down=(new PaymentPermissionMatrixService($p))->load();gcheck($down['authorization_available']===false,'Core permission failure status');gcheck(findRow($down['rows'],'mis_admin','integration.paymongo.manage')['effective_access']==='unavailable','Core failure cannot display allowed');
$api=(string)file_get_contents(ROOT_PATH.'/modules/payment/api/mis_admin/role-permissions.php');$page=(string)file_get_contents(ROOT_PATH.'/modules/payment/pages/mis_admin/roles-permissions.php');$js=(string)file_get_contents(ROOT_PATH.'/modules/payment/assets/js/payment-role-permissions.js');
gcheck(str_contains($api,'AUTHENTICATION_REQUIRED')&&str_contains($api,'NOT_AUTHORIZED')&&str_contains($api,'ACTOR_SESSION_STALE'),'Read API guards');gcheck(str_contains($api,"!=='GET'")&&!preg_match('/INSERT|UPDATE|DELETE\s+FROM/i',$api),'Read endpoint remains GET only');gcheck(str_contains($page,'permissionModule')&&str_contains($page,'permissionSearch')&&str_contains($page,'permissionRoleTabs'),'Comparison and role filters');gcheck(str_contains($page,'role-permission-update.php')&&str_contains($js,'effective_access'),'UI uses server outcomes and update API');gcheck(str_contains($page,'Save permissions')&&str_contains($page,'Review permission changes'),'Permission editor and confirmation');gcheck(is_file(ROOT_PATH.'/modules/payment/pages/mis_admin/payment-user-management.php')&&is_file(ROOT_PATH.'/modules/payment/includes/PaymentPersonnelService.php'),'User Management preserved');
echo "PASS: $n Batch 4G-2 effective permission matrix checks.\n";
