<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')throw new RuntimeException('CLI only');
define('ROOT_PATH',dirname(__DIR__));
require_once ROOT_PATH.'/modules/payment/includes/ocr/ReceiptParserService.php';
require_once ROOT_PATH.'/modules/payment/includes/ocr/OcrTextProviderInterface.php';
$checks=0;
function mis5c(bool $ok,string $message):void{global $checks;$checks++;if(!$ok)throw new RuntimeException($message);}

$parser=new ReceiptParserService();
$parsed=$parser->parse("GCash\nAmount: PHP 1,250.00\nReference No: ABC123456789\n2026-10-04 14:35");
mis5c($parsed['amount']===1250.0,'Amount parsed');
mis5c($parsed['reference_number']==='ABC123456789','Reference parsed');
mis5c($parsed['transaction_date']==='2026-10-04','Date parsed');
mis5c($parsed['transaction_time']==='14:35:00','Time normalized for database storage');
mis5c($parsed['bank_name']==='GCash','Channel parsed');
mis5c($parsed['quality']['parser_version']==='receipt_parser_v1','Parser version recorded');
$empty=$parser->parse('');
mis5c(in_array('NO_TEXT',$empty['quality']['indicators'],true),'No text is reviewable outcome');
$amountOnly=$parser->parse('Amount: PHP 99.25');
mis5c($amountOnly['amount']===99.25&&in_array('REFERENCE_NOT_DETECTED',$amountOnly['quality']['indicators'],true),'Amount-only receipt remains partial');
$referenceOnly=$parser->parse('Reference No: ZXCV123456');
mis5c($referenceOnly['reference_number']==='ZXCV123456'&&in_array('AMOUNT_NOT_DETECTED',$referenceOnly['quality']['indicators'],true),'Reference-only receipt remains partial');
$dateOnly=$parser->parse('2026-10-04');
mis5c($dateOnly['transaction_date']==='2026-10-04'&&in_array('UNKNOWN_RECEIPT_FORMAT',$dateOnly['quality']['indicators'],true),'Unknown provider falls back safely');
final class Mis5cMockProvider implements OcrTextProviderInterface{public int $calls=0;public function extractDocumentText(string $imageBytes):array{$this->calls++;return ['raw_text'=>'Maya Amount: PHP 500.00 Reference No: MOCK123456 2026-10-04','provider'=>'mock','feature'=>'DOCUMENT_TEXT_DETECTION'];}}
$mock=new Mis5cMockProvider();$mockParsed=$parser->parse($mock->extractDocumentText('fixture')['raw_text']);
mis5c($mock->calls===1&&$mockParsed['bank_name']==='Maya','Mock provider fixture executes without Google');

$storage=file_get_contents(ROOT_PATH.'/modules/payment/includes/ocr/PrivateReceiptStorageService.php');
$student=file_get_contents(ROOT_PATH.'/modules/student-portal/pages/student-concern-portal.php');
$viewer=file_get_contents(ROOT_PATH.'/modules/payment/api/accounting/view-receipt.php');
$processor=file_get_contents(ROOT_PATH.'/modules/payment/includes/ocr/ReceiptOcrProcessor.php');
$endpoint=file_get_contents(ROOT_PATH.'/modules/payment/api/accounting/ocr-scan-concern.php');
$service=file_get_contents(ROOT_PATH.'/modules/payment/includes/PaymentConcernService.php');
$verification=file_get_contents(ROOT_PATH.'/modules/payment/includes/PaymentConcernVerificationService.php');
$page=file_get_contents(ROOT_PATH.'/modules/payment/pages/accounting/payment-concern-portal.php');
$guard=file_get_contents(ROOT_PATH.'/modules/payment/includes/ocr/OcrUsageGuardService.php');
$gitignore=file_get_contents(ROOT_PATH.'/.gitignore');
$preflight=file_get_contents(ROOT_PATH.'/tests/payment-mis5-production-preflight.php');
mis5c(str_contains($storage,'5 * 1024 * 1024'),'Five MB limit');
mis5c(str_contains($storage,"'image/webp' => 'webp'"),'WEBP allowed');
mis5c(!str_contains($storage,'application/pdf'),'PDF rejected');
mis5c(str_contains($storage,'new finfo(FILEINFO_MIME_TYPE)'),'Fileinfo used');
mis5c(str_contains($storage,'getimagesize'),'Image structure checked');
mis5c(str_contains($storage,'imagecreatefromstring'),'Image decoding checked');
mis5c(str_contains($storage,'random_bytes(24)'),'Random server filename');
mis5c(str_contains($storage,'PRIVATE_RECEIPT_STORAGE_UNSAFE'),'Web-root storage fails closed');
mis5c(str_contains($storage,'Read-only compatibility'),'Legacy receipt compatibility');
mis5c(str_contains($student,'PrivateReceiptStorageService'),'Student intake uses private storage');
mis5c(!str_contains($student,'application/pdf'),'Student input excludes PDF');
mis5c(str_contains($viewer,'X-Content-Type-Options: nosniff'),'Viewer sends nosniff');
mis5c(str_contains($viewer,'Cache-Control: private, no-store'),'Viewer prevents shared caching');
mis5c(str_contains($processor,"hash('sha256',\$bytes)"),'Image SHA-256 computed server-side');
mis5c(str_contains($processor,'OcrUsageGuardService'),'Usage guard integrated');
mis5c(str_contains($processor,'OCR_PROVIDER_NOT_CONFIGURED'),'Provider readiness fails before reservation');
mis5c(str_contains($processor,"'CONTROLLED_RETRY':'RECEIPT_SCAN'"),'Retry is explicit');
mis5c(str_contains($processor,'writeCompatibility'),'Legacy ocr_results projection preserved');
mis5c(str_contains($processor,'OCR evidence is ready for Accounting review'),'Evidence-only result');
mis5c(str_contains($endpoint,'OcrStructuredAuditService'),'Structured audit outbox integrated');
mis5c(!str_contains($endpoint,'BankReconciliationService'),'OCR endpoint has no AUB coupling');
mis5c(!str_contains($service,'BankReconciliationService'),'Concern decision has no AUB dependency');
mis5c(!str_contains($page,'AUB'),'Accounting OCR review is AUB-neutral');
mis5c(str_contains($page,'review_confirmed'),'Accounting review confirmation required');
mis5c(str_contains($page,'retry: retry === true'),'Retry is explicit in Accounting UI');
mis5c(str_contains($service,"payment_status = 'Verified'"),'Duplicate verified reference check remains');
mis5c(!str_contains($service,'Run OCR and review the receipt before approval.'),'Manual Accounting approval remains available when OCR is unavailable');
mis5c(!str_contains($page,"if (\$row['ocr_status'] === 'Completed')"),'Accounting Verify action is not hidden behind OCR success');
mis5c(str_contains($verification,"EXACT_IMAGE_DUPLICATE")&&str_contains($verification,"REFERENCE_DUPLICATE"),'Accounting rule engine displays structured duplicate indicators');
mis5c(str_contains($guard,"receipt_parser_v1"),'Attempt records parser version');
mis5c(str_contains($guard,'OCR_PROVIDER_UNAVAILABLE'),'Provider failure creates a structured manual-review indicator');
mis5c(str_contains($endpoint,'recordFailure'),'OCR failures use the structured audit/outbox fallback');
mis5c(str_contains($gitignore,'/modules/payment/database/payment_db-*.sql'),'Generated dumps ignored narrowly');
mis5c(!str_contains($processor,'GOOGLE_APPLICATION_CREDENTIALS'),'Processor does not handle secrets');
mis5c(str_contains($preflight,"'vision_image_request_made'=>false"),'Production preflight explicitly remains non-billable');
mis5c(!str_contains($preflight,'documentTextDetection'),'Production preflight cannot submit an image to Vision');
mis5c(str_contains($preflight,'nonBillableAuthenticationStatus'),'Production preflight validates Google OAuth without exposing the token');
mis5c(str_contains($preflight,"ssl://'.\$host.':443"),'Production preflight checks TLS connectivity without submitting an image');
mis5c(str_contains($preflight,"'ocr_enabled'")&&str_contains($preflight,"'ocr_monthly_limit'"),'Production preflight checks disabled state and usage limit');
mis5c(str_contains($preflight,'ocr_usage_months')&&str_contains($preflight,'ocr_image_cache'),'Production preflight checks OCR database foundation');
echo "PASS: $checks MIS-5C secure receipt and OCR processing checks.\n";
