<?php
require_once __DIR__ . '/../../../../config/config.php'; require_once ROOT_PATH . '/includes/authentication.php'; require_once __DIR__ . '/../../database/db_connect.php';
requireAuth(); requirePaymentPermission('payment.school_sales_catalog');
$message='';
if($_SERVER['REQUEST_METHOD']==='POST') try { if(!verifyCsrfToken($_POST['csrf_token']??'')) throw new RuntimeException('Invalid CSRF token.'); if(($_POST['action']??'')==='category'){ $stmt=$pdo->prepare('INSERT INTO school_sale_categories (category_name,sort_order) VALUES (?,?)');$stmt->execute([trim($_POST['category_name']), (int)$_POST['sort_order']]); } elseif(($_POST['action']??'')==='item'){ $stmt=$pdo->prepare("INSERT INTO school_sale_items (sale_category_id,item_name,unit_price,status) VALUES (?,?,?,'Active')");$stmt->execute([(int)$_POST['sale_category_id'],trim($_POST['item_name']),(float)$_POST['unit_price']]); } $message='Saved.'; } catch(Throwable $e){$message=$e->getMessage();}
$categories=[];$items=[];try{$categories=$pdo->query('SELECT * FROM school_sale_categories ORDER BY sort_order,category_name')->fetchAll(PDO::FETCH_ASSOC);$items=$pdo->query('SELECT i.*,c.category_name FROM school_sale_items i JOIN school_sale_categories c ON c.sale_category_id=i.sale_category_id ORDER BY c.sort_order,i.item_name')->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable $e){$message='Apply the cashier school-sales migration first.';}
$pageTitle='School Sales Catalog';$activeModule='payment';$activePage='payment_admin/school-sales-catalog';$breadcrumbs=[['label'=>'Payment Management','url'=>BASE_URL.'/modules/payment/index.php'],['label'=>'School Sales Catalog','url'=>null]];require_once ROOT_PATH.'/includes/breadcrumbs.php';require_once ROOT_PATH.'/includes/layout-start.php';
?>
<?php renderBreadcrumbs($breadcrumbs); ?><div class="container-fluid py-4"><h2 class="fw-bolder">School Sales Catalog</h2><p class="text-muted">Approved cash-sale items only. These never affect academic billing or student balances.</p><?php if($message):?><div class="alert alert-info"><?=htmlspecialchars($message)?></div><?php endif;?><div class="row g-4"><div class="col-md-4"><div class="card"><div class="card-body"><h5>Add Category</h5><form method="post"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(generateCsrfToken())?>"><input type="hidden" name="action" value="category"><input class="form-control mb-2" name="category_name" placeholder="e.g. Uniform" required><input class="form-control mb-2" type="number" name="sort_order" value="0"><button class="btn btn-primary">Save Category</button></form></div></div></div><div class="col-md-8"><div class="card"><div class="card-body"><h5>Add Approved Item</h5><form method="post" class="row g-2"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(generateCsrfToken())?>"><input type="hidden" name="action" value="item"><div class="col-md-4"><select name="sale_category_id" class="form-select" required><option value="">Category</option><?php foreach($categories as $c):?><option value="<?=$c['sale_category_id']?>"><?=htmlspecialchars($c['category_name'])?></option><?php endforeach;?></select></div><div class="col-md-4"><input class="form-control" name="item_name" placeholder="Item name" required></div><div class="col-md-2"><input class="form-control" type="number" min="0.01" step="0.01" name="unit_price" placeholder="Price" required></div><div class="col-md-2"><button class="btn btn-success w-100">Add Item</button></div></form></div></div></div></div><div class="card mt-4"><div class="card-body"><h5>Configured Items</h5><table class="table"><thead><tr><th>Category</th><th>Item</th><th>Price</th><th>Status</th></tr></thead><tbody><?php foreach($items as $i):?><tr><td><?=htmlspecialchars($i['category_name'])?></td><td><?=htmlspecialchars($i['item_name'])?></td><td>PHP <?=number_format((float)$i['unit_price'],2)?></td><td><?=htmlspecialchars($i['status'])?></td></tr><?php endforeach;?></tbody></table></div></div></div><?php require_once ROOT_PATH.'/includes/layout-end.php'; ?>
