<?php
require_once __DIR__ . '/../../../../config/config.php'; require_once ROOT_PATH . '/includes/authentication.php'; requireAuth(); requirePaymentPermission('payment.cashier_dashboard');
$pageTitle='Cashier Dashboard'; $activeModule='payment'; $activePage='cashier/dashboard'; $breadcrumbs=[['label'=>'Payment Management','url'=>BASE_URL.'/modules/payment/index.php'],['label'=>'Cashier Dashboard','url'=>null]]; require_once ROOT_PATH.'/includes/breadcrumbs.php'; require_once ROOT_PATH.'/includes/layout-start.php';
?>
<?php renderBreadcrumbs($breadcrumbs); ?>
<div class="container-fluid py-4"><div class="d-flex justify-content-between align-items-center mb-4"><div><h2 class="fw-bolder mb-1">Cashier Dashboard</h2><p class="text-muted mb-0">Your verified cash collections and student-linked school sales.</p></div><select id="period" class="form-select w-auto"><option value="today">Today</option><option value="week">This Week</option><option value="month">This Month</option><option value="year">This Year</option></select></div>
<div class="row g-3 mb-4"><div class="col-md-3"><div class="card border-start border-4 border-primary shadow-sm"><div class="card-body"><small>Academic Cash Collections</small><h3 id="academic">PHP 0.00</h3><small id="academicCompare" class="text-muted">Compared with last year</small></div></div></div><div class="col-md-3"><div class="card border-start border-4 border-success shadow-sm"><div class="card-body"><small>School Sales</small><h3 id="sales">PHP 0.00</h3><small id="salesCompare" class="text-muted">Compared with last year</small></div></div></div><div class="col-md-3"><div class="card border-start border-4 border-dark shadow-sm"><div class="card-body"><small>Total Cash Received</small><h3 id="total">PHP 0.00</h3><small id="transactions">0 transactions / ORs</small></div></div></div><div class="col-md-3"><div class="card border-start border-4 border-danger shadow-sm"><div class="card-body"><small>School-wide Academic Balance</small><h3 id="outstanding">PHP 0.00</h3><small id="efficiency">Collection efficiency: 0%</small></div></div></div></div>
<div class="alert alert-light border">School Sales are intentionally separate from academic balance and collection efficiency. Sales and academic cash comparisons use the same selected period last year.</div><div class="card shadow-sm border-0"><div class="card-body"><h5>School Sales by Category</h5><canvas id="salesChart" height="110"></canvas></div></div></div>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script>let chart; const money=v=>'PHP '+Number(v||0).toLocaleString('en-PH',{minimumFractionDigits:2}); async function load(){const d=await (await fetch('<?= BASE_URL ?>/modules/payment/api/cashier-dashboard-data.php?period='+period.value)).json();if(d.error){alert(d.error);return}academic.textContent=money(d.kpis.academic);sales.textContent=money(d.kpis.sales);total.textContent=money(d.kpis.total);transactions.textContent=d.kpis.transactions+' transactions / ORs';outstanding.textContent=money(d.kpis.outstanding);efficiency.textContent='Collection efficiency: '+d.kpis.efficiency.toFixed(1)+'% ('+(d.comparison.efficiency_points>=0?'+':'')+d.comparison.efficiency_points.toFixed(1)+' pts vs last year)';salesCompare.textContent=d.comparison.sales_percent===null?'No prior-year sales':(d.comparison.sales_percent>=0?'↑ ':'↓ ')+Math.abs(d.comparison.sales_percent).toFixed(1)+'% vs last year';academicCompare.textContent=d.comparison.academic_percent===null?'No prior-year academic cash':(d.comparison.academic_percent>=0?'↑ ':'↓ ')+Math.abs(d.comparison.academic_percent).toFixed(1)+'% vs last year'; if(chart)chart.destroy();chart=new Chart(document.getElementById('salesChart'),{type:'bar',data:{labels:d.sales_categories.map(x=>x.label),datasets:[{label:'Sales',data:d.sales_categories.map(x=>x.total),backgroundColor:'#198754'}]}})}period.onchange=load;load();</script>
<?php require_once ROOT_PATH.'/includes/layout-end.php'; ?>
