<?php
require_once __DIR__ . '/../../../../config/config.php';
require_once ROOT_PATH . '/includes/authentication.php';
requireAuth();
requirePaymentPermission('payment.cashier_dashboard');
$pageTitle='Cashier Dashboard'; $activeModule='payment'; $activePage='cashier/dashboard';
$breadcrumbs=[['label'=>'Payment Management','url'=>BASE_URL.'/modules/payment/index.php'],['label'=>'Cashier Dashboard','url'=>null]];
require_once ROOT_PATH . '/includes/breadcrumbs.php'; require_once ROOT_PATH . '/includes/layout-start.php';
?>
<?php renderBreadcrumbs($breadcrumbs); ?>
<div class="container-fluid py-4 cashier-dashboard">
  <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4">
    <div><h2 class="fw-bolder mb-1"><i class="ti ti-cash-register text-primary me-2"></i>Cashier Dashboard</h2><p class="text-muted mb-0">My walk-in cash activity — <strong><?= htmlspecialchars(getCurrentUserName()) ?></strong></p></div>
    <div class="btn-group" role="group" aria-label="Collection period">
      <button class="btn btn-outline-primary period-btn active" data-period="today">Today</button><button class="btn btn-outline-primary period-btn" data-period="week">Week</button><button class="btn btn-outline-primary period-btn" data-period="month">Month</button><button class="btn btn-outline-primary period-btn" data-period="year">Year</button>
    </div>
  </div>
  <div id="dashboardAlert" class="alert alert-danger d-none"></div><div id="integrityAlert" class="alert alert-warning d-none"></div>
  <div class="d-flex justify-content-between align-items-center mb-3"><small id="periodLabel" class="text-muted"></small><small class="text-muted">Reporting timezone: Asia/Manila</small></div>
  <div class="row g-3 mb-4">
    <div class="col-md-6 col-xl"><div class="card h-100 border-0 shadow-sm border-start border-4 border-primary"><div class="card-body"><small class="text-muted text-uppercase fw-bold">Academic Cash</small><h3 id="academicKpi" class="mt-2 mb-1">PHP 0.00</h3><small id="academicCompare" class="text-muted">Comparable period</small></div></div></div>
    <div class="col-md-6 col-xl"><div class="card h-100 border-0 shadow-sm border-start border-4" style="border-color:#0891b2!important"><div class="card-body"><small class="text-muted text-uppercase fw-bold">School Sales</small><h3 id="salesKpi" class="mt-2 mb-1">PHP 0.00</h3><small id="salesCompare" class="text-muted">Comparable period</small></div></div></div>
    <div class="col-md-6 col-xl"><div class="card h-100 border-0 shadow-sm border-start border-4 border-success"><div class="card-body"><small class="text-muted text-uppercase fw-bold">Total Cash</small><h3 id="totalKpi" class="mt-2 mb-1">PHP 0.00</h3><small id="totalCompare" class="text-muted">Comparable period</small></div></div></div>
    <div class="col-md-6 col-xl"><div class="card h-100 border-0 shadow-sm border-start border-4 border-dark"><div class="card-body"><small class="text-muted text-uppercase fw-bold">Successful Txns</small><h3 id="transactionKpi" class="mt-2 mb-1">0</h3><small class="text-muted">Verified walk-ins + completed sales</small></div></div></div>
    <div class="col-md-6 col-xl"><div class="card h-100 border-0 shadow-sm border-start border-4 border-warning"><div class="card-body"><small class="text-muted text-uppercase fw-bold">Original Receipts Rendered</small><h3 id="receiptKpi" class="mt-2 mb-1">0</h3><small class="text-muted">First authorized receipt renders only</small></div></div></div>
  </div>
  <div class="card border-0 shadow-sm mb-4"><div class="card-body"><h5 class="mb-1">Total Cash Collection Trend</h5><p id="trendSubtitle" class="small text-muted">Current period versus comparable prior period.</p><div style="height:310px"><canvas id="trendChart"></canvas></div></div></div>
  <div class="row g-4 mb-4">
    <div class="col-xl-6"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h5 class="mb-1">Academic Collections by Fee Category</h5><p class="small text-muted">Verified academic allocations only.</p><div style="height:280px"><canvas id="academicCategoryChart"></canvas></div></div></div></div>
    <div class="col-xl-6"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h5 class="mb-1">School Sales by Catalog Category</h5><p class="small text-muted">Completed sales only; excluded from academic balances.</p><div style="height:280px"><canvas id="salesCategoryChart"></canvas></div></div></div></div>
  </div>
  <div class="card border-0 shadow-sm mb-4"><div class="card-body">
    <div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><div><h5 class="mb-1">Student Quick Lookup</h5><p class="small text-muted mb-0">Basic balance and unpaid-category summary only.</p></div><div class="d-flex gap-2"><a class="btn btn-sm btn-outline-secondary" href="<?= BASE_URL ?>/modules/payment/pages/cashier/walk-in-transaction-history.php"><i class="ti ti-history me-1"></i>History</a></div></div>
    <div class="input-group"><input id="studentQuery" class="form-control" placeholder="Student number or name" autocomplete="off"><button id="studentSearch" class="btn btn-primary" type="button"><i class="ti ti-search me-1"></i>Search</button></div>
    <div id="studentResults" class="list-group mt-2 d-none"></div><div id="studentLookupMessage" class="small text-muted mt-2"></div>
    <div id="studentSummary" class="border rounded p-3 mt-3 d-none"><div class="d-flex flex-wrap justify-content-between gap-3"><div><h5 id="lookupName" class="mb-1"></h5><div id="lookupMeta" class="text-muted"></div><div id="lookupTerm" class="small text-muted mt-1"></div></div><div class="text-end"><small class="text-muted text-uppercase fw-bold">Outstanding</small><h4 id="lookupBalance" class="text-danger mb-0"></h4></div></div><hr><h6>Unpaid Categories</h6><div id="lookupCategories" class="d-flex flex-wrap gap-2"></div><div class="d-flex flex-wrap gap-2 mt-3"><a id="collectAction" class="btn btn-primary"><i class="ti ti-cash me-1"></i>Collect Payment</a><a id="detailsAction" class="btn btn-outline-primary"><i class="ti ti-file-description me-1"></i>Full Details</a><a id="saleAction" class="btn btn-outline-secondary"><i class="ti ti-shopping-cart me-1"></i>New School Sale</a></div></div>
  </div></div>
  <div class="card border-0 shadow-sm"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><div><h5 class="mb-1">Recent Walk-in Transactions</h5><p class="small text-muted mb-0">Same successful records used by this dashboard.</p></div><a href="<?= BASE_URL ?>/modules/payment/pages/cashier/walk-in-transaction-history.php" class="btn btn-sm btn-outline-primary">View All</a></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Date / Time</th><th>OR / Reference</th><th>Student</th><th>Type</th><th>Category / Items</th><th class="text-end">Amount</th><th class="text-center">Receipt</th></tr></thead><tbody id="recentTransactions"><tr><td colspan="7" class="text-center text-muted py-4">Loading transactions…</td></tr></tbody></table></div></div></div>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
(() => {
 const base='<?= BASE_URL ?>', money=v=>'PHP '+Number(v||0).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2});
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 let period='today',trendChart,academicChart,salesChart;
 const chart=(old,id,config)=>{if(old)old.destroy();return new Chart(document.getElementById(id),config)};
 const comparison=(entry,label)=>{const current=Number(entry.current||0),prior=Number(entry.prior||0);if(prior<=0)return 'No comparable prior data';const pct=Math.abs((current-prior)/prior*100).toFixed(1);return (current>=prior?'↑ ':'↓ ')+pct+'% '+label};
 const fallback=(rows,label)=>rows.length?rows:[{label,total:0}];
 async function loadDashboard(){const alert=document.getElementById('dashboardAlert');alert.classList.add('d-none');try{const response=await fetch(base+'/modules/payment/api/cashier-dashboard-data.php?period='+encodeURIComponent(period),{credentials:'same-origin'});const data=await response.json();if(!response.ok||data.error)throw new Error(data.error||'Unable to load dashboard data.');
  document.getElementById('periodLabel').textContent='['+data.range.start_at+', '+data.range.end_exclusive+') · Asia/Manila';
  document.getElementById('academicKpi').textContent=money(data.kpis.academic);document.getElementById('salesKpi').textContent=money(data.kpis.sales);document.getElementById('totalKpi').textContent=money(data.kpis.total_cash);document.getElementById('transactionKpi').textContent=Number(data.kpis.transactions).toLocaleString();document.getElementById('receiptKpi').textContent=Number(data.kpis.receipts).toLocaleString();
  ['academic','sales','total'].forEach(k=>document.getElementById(k+'Compare').textContent=comparison(data.comparison[k],data.comparison_label));document.getElementById('trendSubtitle').textContent='Current period '+data.comparison_label+'.';
  const integrity=document.getElementById('integrityAlert'),missing=Number(data.data_integrity?.verified_walkins_missing_verified_at||0),mismatches=Number(data.data_integrity?.allocation_mismatch_count||0);integrity.classList.toggle('d-none',!missing&&!mismatches);integrity.textContent=[missing?missing+' verified walk-in payment(s) are excluded because verified_at is missing.':'',mismatches?mismatches+' verified walk-in payment(s) have a header/allocation amount mismatch. Academic totals use allocated amounts.':'' ].filter(Boolean).join(' ');
  trendChart=chart(trendChart,'trendChart',{type:'line',data:{labels:data.trend.current.labels,datasets:[{label:'Current period',data:data.trend.current.values,borderColor:'#2563EB',backgroundColor:'rgba(37,99,235,.12)',fill:true,tension:.3,borderWidth:2},{label:'Comparable prior',data:data.trend.prior.values,borderColor:'#94A3B8',borderDash:[6,5],tension:.3,borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},scales:{y:{beginAtZero:true,ticks:{callback:v=>'PHP '+Number(v).toLocaleString()}}}}});
  const academic=fallback(data.academic_categories,'No academic collections');academicChart=chart(academicChart,'academicCategoryChart',{type:'bar',data:{labels:academic.map(r=>r.label),datasets:[{data:academic.map(r=>r.total),backgroundColor:'#2563EB',borderRadius:5}]},options:{indexAxis:'y',responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{beginAtZero:true,ticks:{callback:v=>'PHP '+Number(v).toLocaleString()}}}}});
  const sales=fallback(data.sale_categories,'No school sales');salesChart=chart(salesChart,'salesCategoryChart',{type:'bar',data:{labels:sales.map(r=>r.label),datasets:[{data:sales.map(r=>r.total),backgroundColor:'#0891B2',borderRadius:5}]},options:{indexAxis:'y',responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{beginAtZero:true,ticks:{callback:v=>'PHP '+Number(v).toLocaleString()}}}}});
  const recent=document.getElementById('recentTransactions');recent.innerHTML=data.recent_transactions.length?data.recent_transactions.map(row=>{const url=row.transaction_type==='School Sale'?base+'/modules/payment/pages/cashier/print-receipt.php?cash_sale_id='+row.record_id:base+'/modules/payment/pages/cashier/print-receipt.php?payment_id='+row.record_id;const mismatch=Number(row.allocation_mismatch)===1;const amountInfo=mismatch?'<small class="d-block text-danger">Allocation mismatch · Header '+money(row.header_amount)+' · Allocated '+money(row.total)+' · Difference '+money(row.amount_difference)+'</small>':'';return '<tr><td>'+esc(row.happened_at)+'</td><td class="fw-semibold">'+esc(row.receipt)+'</td><td>'+esc(row.full_name)+'<small class="d-block text-muted">'+esc(row.student_number)+'</small></td><td><span class="badge '+(row.transaction_type==='School Sale'?'bg-info':'bg-primary')+'">'+esc(row.transaction_type)+'</span></td><td class="small">'+esc(row.details||'—')+'</td><td class="text-end fw-semibold">'+money(row.total)+amountInfo+'</td><td class="text-center"><a class="btn btn-sm btn-outline-primary" target="_blank" href="'+url+'"><i class="ti ti-printer"></i></a></td></tr>'}).join(''):'<tr><td colspan="7" class="text-center text-muted py-4">No successful cashier transactions for this period.</td></tr>';
 }catch(error){alert.textContent=error.message;alert.classList.remove('d-none')}}
 document.querySelectorAll('.period-btn').forEach(button=>button.addEventListener('click',()=>{period=button.dataset.period;document.querySelectorAll('.period-btn').forEach(x=>x.classList.toggle('active',x===button));loadDashboard()}));
 const query=document.getElementById('studentQuery'),results=document.getElementById('studentResults'),message=document.getElementById('studentLookupMessage');
 async function loadStudent(number){message.textContent='Loading financial summary…';results.classList.add('d-none');const response=await fetch(base+'/modules/payment/api/fetch_collection_billing.php?student_number='+encodeURIComponent(number),{credentials:'same-origin'});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||'Student billing is unavailable.');document.getElementById('lookupName').textContent=data.name+' ('+data.student_number+')';document.getElementById('lookupMeta').textContent=data.course_year;document.getElementById('lookupTerm').textContent=[data.academic_year,data.semester].filter(Boolean).join(' • ');document.getElementById('lookupBalance').textContent=money(data.balance);document.getElementById('lookupCategories').innerHTML=(data.breakdown?.categories||[]).map(c=>'<span class="badge bg-light text-dark border">'+esc(c.category_name)+' · '+money(c.category_total)+'</span>').join('')||'<span class="text-muted small">No unpaid categories.</span>';const encoded=encodeURIComponent(data.student_number);document.getElementById('collectAction').href=base+'/modules/payment/pages/cashier/payment-collection-portal.php?student_number='+encoded;document.getElementById('detailsAction').href=base+'/modules/payment/pages/cashier/payment-collection-portal.php?student_number='+encoded+'&mode=details';document.getElementById('saleAction').href=base+'/modules/payment/pages/cashier/school-sales.php?student_number='+encoded;document.getElementById('studentSummary').classList.remove('d-none');message.textContent='';}
 async function search(){document.getElementById('studentSummary').classList.add('d-none');message.textContent='Searching…';try{const response=await fetch(base+'/modules/payment/api/cashier-student-search.php?q='+encodeURIComponent(query.value.trim()),{credentials:'same-origin'});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||'Search failed.');if(!data.students.length){message.textContent='No matching student found.';results.classList.add('d-none');return}if(data.students.length===1){await loadStudent(data.students[0].student_number);return}results.innerHTML=data.students.map(s=>'<button type="button" class="list-group-item list-group-item-action" data-number="'+esc(s.student_number)+'"><strong>'+esc(s.full_name)+'</strong><small class="d-block text-muted">'+esc(s.student_number)+' · '+esc(s.course)+' · Year '+esc(s.year_level)+'</small></button>').join('');results.classList.remove('d-none');message.textContent='Select a student.';results.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>loadStudent(b.dataset.number).catch(e=>message.textContent=e.message)))}catch(error){message.textContent=error.message;results.classList.add('d-none')}}
 document.getElementById('studentSearch').addEventListener('click',search);query.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();search()}});loadDashboard();
})();
</script>
<?php require_once ROOT_PATH . '/includes/layout-end.php'; ?>
