<?php
declare(strict_types=1);
require_once __DIR__.'/PaymentReportingScope.php';require_once __DIR__.'/AccountingReportingPeriod.php';
final class AccountingReportingService
{
 public function __construct(private PDO $pdo){}
 private function rows(string $sql,array $params=[]):array{$q=$this->pdo->prepare($sql);$q->execute($params);return$q->fetchAll(PDO::FETCH_ASSOC);}
 private function num(string $sql,array $params=[]):float{$q=$this->pdo->prepare($sql);$q->execute($params);return(float)($q->fetchColumn()?:0);}
 public function filters(array $i):array{$ay=trim((string)($i['academic_year']??''));$sem=(string)($i['semester']??'');if($ay===''||!in_array($sem,['1st','2nd','Summer'],true)){$t=$this->rows('SELECT academic_year,semester FROM billing ORDER BY academic_year DESC,billing_id DESC LIMIT 1');$ay=$ay?:($t[0]['academic_year']??'');$sem=in_array($sem,['1st','2nd','Summer'],true)?$sem:($t[0]['semester']??'1st');}if($ay==='')throw new InvalidArgumentException('No academic billing cohort is available.');$r=AccountingReportingPeriod::fromRequest($i);foreach(['payment_channel','payment_method','search']as$key)if(isset($i[$key])&&!is_string($i[$key])&&!is_int($i[$key]))throw new InvalidArgumentException('A report filter is invalid.');$channel=trim((string)($i['payment_channel']??''));$category=filter_var($i['fee_category']??null,FILTER_VALIDATE_INT);$method=trim((string)($i['payment_method']??''));$search=trim((string)($i['search']??''));if(strlen($method)>50||strlen($search)>100)throw new InvalidArgumentException('A report filter is too long.');return['academic_year'=>$ay,'semester'=>$sem,'range'=>$r,'payment_channel'=>$channel?:null,'payment_method'=>$method?:null,'search'=>$search,'fee_category'=>$category&&$category>0?$category:null];}
 private function base(array $f,array &$p):array{$p=[$f['academic_year'],$f['semester']];$join=' FROM payment_allocations pa JOIN payments p ON p.payment_id=pa.payment_id JOIN billing_items bi ON bi.billing_item_id=pa.billing_item_id JOIN billing b ON b.billing_id=bi.billing_id JOIN fees f ON f.fee_id=bi.fee_id LEFT JOIN fee_categories fc ON fc.category_id=f.category_id ';$where=' WHERE '.PaymentReportingScope::officialCondition('p').' AND b.academic_year=? AND b.semester=?';if($f['payment_channel']){$where.=' AND p.payment_channel=?';$p[]=$f['payment_channel'];}if($f['payment_method']){$where.=' AND p.payment_method=?';$p[]=$f['payment_method'];}if($f['search']!==''){$where.=' AND (p.reference_number LIKE ? OR p.receipt_number LIKE ? OR EXISTS (SELECT 1 FROM students sr WHERE sr.student_id=p.student_id AND (sr.student_number LIKE ? OR sr.full_name LIKE ?)))';$like='%'.$f['search'].'%';array_push($p,$like,$like,$like,$like);}if($f['fee_category']){$where.=' AND f.category_id=?';$p[]=$f['fee_category'];}return[$join,$where];}
 private function collections(array $f,DateTimeImmutable $start,DateTimeImmutable $end):float{$p=[];[$j,$w]=$this->base($f,$p);$p[]=AccountingReportingPeriod::sql($start);$p[]=AccountingReportingPeriod::sql($end);return$this->num('SELECT COALESCE(SUM(pa.allocated_amount),0)'.$j.$w.' AND p.verified_at>=? AND p.verified_at<?',$p);}
 public function report(array $i):array{return $this->reportNormalized($this->filters($i));}
 public function reportNormalized(array $f):array{return $this->withRecent($this->reportCoreNormalized($f),$this->recentCollectionsAll($f));}
 public function reportPageNormalized(array $f,int $page,int $pageSize):array
 {
  $total=$this->recentCollectionsCount($f);$pages=$total===0?0:(int)ceil($total/$pageSize);$page=$pages===0?1:min($page,$pages);
  $recent=$total===0?[]:$this->recentCollectionsPage($f,$page,$pageSize);
  $d=$this->withRecent($this->reportCoreNormalized($f),$recent);
  $d['recent_collections_pagination']=['page'=>$page,'page_size'=>$pageSize,'total_records'=>$total,'total_pages'=>$pages,'has_previous'=>$page>1,'has_next'=>$pages>0&&$page<$pages];
  return$d;
 }
 private function reportCoreNormalized(array $f):array
 {
  $r=$f['range'];$net=$this->num('SELECT COALESCE(SUM(total_amount-COALESCE(discount_amount,0)),0) FROM billing WHERE academic_year=? AND semester=?',[$f['academic_year'],$f['semester']]);$out=$this->num("SELECT COALESCE(SUM(remaining_balance),0) FROM billing WHERE academic_year=? AND semester=? AND billing_status IN ('Unpaid','Partial')",[$f['academic_year'],$f['semester']]);$current=$this->collections($f,$r['start_at'],$r['end_exclusive']);$cutoff=$this->termCutoff($f,$r['end_exclusive']);$eff=$net>0?$cutoff/$net*100:null;$countParams=[];[$countJoin,$countWhere]=$this->base($f,$countParams);$countParams[]=AccountingReportingPeriod::sql($r['start_at']);$countParams[]=AccountingReportingPeriod::sql($r['end_exclusive']);$paymentCount=(int)$this->num('SELECT COUNT(DISTINCT p.payment_id)'.$countJoin.$countWhere.' AND p.verified_at>=? AND p.verified_at<?',$countParams);$average=$paymentCount>0?$current/$paymentCount:null;
  $p=[];[$j,$w]=$this->base($f,$p);$p[]=AccountingReportingPeriod::sql($r['start_at']);$p[]=AccountingReportingPeriod::sql($r['end_exclusive']);$categories=$this->rows("SELECT COALESCE(NULLIF(fc.category_name,''),'Unmapped category') label,SUM(pa.allocated_amount) total".$j.$w.' AND p.verified_at>=? AND p.verified_at<? GROUP BY COALESCE(NULLIF(fc.category_name,\'\'),\'Unmapped category\') ORDER BY total DESC',$p);
  $p=[];[$j,$w]=$this->base($f,$p);$p[]=AccountingReportingPeriod::sql($r['start_at']);$p[]=AccountingReportingPeriod::sql($r['end_exclusive']);$channels=$this->rows('SELECT p.payment_channel label,SUM(pa.allocated_amount) total'.$j.$w.' AND p.verified_at>=? AND p.verified_at<? GROUP BY p.payment_channel ORDER BY total DESC',$p);
  return['timezone'=>AccountingReportingPeriod::TIMEZONE,'scope'=>['academic_year'=>$f['academic_year'],'semester'=>$f['semester'],'period'=>$r['period'],'period_month'=>$r['period_month'],'period_year'=>$r['period_year'],'period_label'=>$r['period_label'],'start_at'=>AccountingReportingPeriod::sql($r['start_at']),'end_exclusive'=>AccountingReportingPeriod::sql($r['end_exclusive']),'payment_channel'=>$f['payment_channel'],'payment_method'=>$f['payment_method'],'search'=>$f['search'],'fee_category'=>$f['fee_category']],'section_status'=>['kpis'=>'ok','fee_categories'=>$categories?'ok':'no_data','payment_channels'=>$channels?'ok':'no_data'],'kpis'=>['net_assessed_amount'=>$net,'outstanding_balance'=>$out,'official_academic_collections'=>$current,'verified_payment_count'=>$paymentCount,'average_payment_amount'=>$average,'term_to_date_collections'=>$cutoff,'collection_efficiency'=>$eff,'snapshot_note'=>'Net Assessed Amount and Outstanding Balance are AY/Semester snapshots; category filters apply only to collections.'],'fee_categories'=>$categories,'payment_channels'=>$channels,'trend'=>['labels'=>[],'current'=>[],'prior'=>[],'comparison_label'=>$r['comparison_label']],'integrity_warnings'=>$eff!==null&&$eff>100?['Collection Efficiency exceeds 100%.']:[]];
 }
 private function withRecent(array $d,array $recent):array{$d['recent_collections']=$recent;$d['section_status']['recent_collections']=$recent?'ok':'no_data';return$d;}
 private function recentCollectionsScope(array $f):array
 {
  $p=[];[$j,$w]=$this->base($f,$p);$p[]=AccountingReportingPeriod::sql($f['range']['start_at']);$p[]=AccountingReportingPeriod::sql($f['range']['end_exclusive']);
  return[$j.' JOIN students s ON s.student_id=p.student_id ',$w.' AND p.verified_at>=? AND p.verified_at<?',$p];
 }
 private function recentCollectionsSelect():string{return 'SELECT p.payment_id,p.verified_at,p.receipt_number,p.reference_number,p.transaction_type,p.payment_channel,p.payment_method,p.payment_status,p.verified_by,MAX(b.academic_year) academic_year,MAX(b.semester) semester,MAX(s.student_number) student_number,MAX(s.full_name) full_name,GROUP_CONCAT(DISTINCT COALESCE(NULLIF(fc.category_name,\'\'),\'Unmapped category\') ORDER BY COALESCE(NULLIF(fc.category_name,\'\'),\'Unmapped category\') SEPARATOR \', \') allocation_breakdown,SUM(pa.allocated_amount) total_applied';}
 private function recentCollectionsGroupOrder():string{return ' GROUP BY p.payment_id,p.verified_at,p.receipt_number,p.reference_number,p.transaction_type,p.payment_channel,p.payment_method,p.payment_status,p.verified_by ORDER BY p.verified_at DESC,p.payment_id DESC';}
 private function recentCollectionsAll(array $f):array{[$j,$w,$p]=$this->recentCollectionsScope($f);return$this->rows($this->recentCollectionsSelect().$j.$w.$this->recentCollectionsGroupOrder(),$p);}
 private function recentCollectionsCount(array $f):int{[$j,$w,$p]=$this->recentCollectionsScope($f);return(int)$this->num('SELECT COUNT(DISTINCT p.payment_id)'.$j.$w,$p);}
 private function recentCollectionsPage(array $f,int $page,int $pageSize):array
 {
  [$j,$w,$p]=$this->recentCollectionsScope($f);$q=$this->pdo->prepare($this->recentCollectionsSelect().$j.$w.$this->recentCollectionsGroupOrder().' LIMIT ? OFFSET ?');$position=1;foreach($p as $value)$q->bindValue($position++,$value);$q->bindValue($position++,$pageSize,PDO::PARAM_INT);$q->bindValue($position,($page-1)*$pageSize,PDO::PARAM_INT);$q->execute();return$q->fetchAll(PDO::FETCH_ASSOC);
 } private function termCutoff(array $f,DateTimeImmutable $end):float{$p=[];[$j,$w]=$this->base($f,$p);$p[]=AccountingReportingPeriod::sql($end);return$this->num('SELECT COALESCE(SUM(pa.allocated_amount),0)'.$j.$w.' AND p.verified_at<?',$p);}
}
