<?php
/**
 * Google OCR Service (with Free Mock Mode Fallback)
 * Handles text extraction from payment receipts.
 */
class GoogleOCRService {
    private $pdo;
    private $mockMode = true; // Set to true to bypass Google Cloud billing requirement

    public function __construct($pdo) {
        $this->pdo = $pdo;
    }

    /**
     * Processes the receipt image and extracts text.
     * Since billing is disabled on GCP, this uses an Intelligent Mock Mode
     * to simulate Google Vision API's behavior for capstone testing.
     * 
     * @param int $concernId The ID of the payment concern ticket
     * @param string $receiptPath The relative path of the uploaded receipt
     * @return int The ID of the inserted ocr_results record, or false on failure
     */
    public function processReceipt($concernId, $receiptPath) {
        try {
            // Simulate processing time
            sleep(1);

            $extractedAmount = 0;
            $bankName = 'Unknown';
            $confidence = 0;
            $referenceNumber = 'N/A';
            $date = date('Y-m-d');
            $time = date('H:i:s');
            $rawJson = '{}';

            if ($this->mockMode) {
                // Intelligent Mock Data for Capstone Defense/Testing
                // We will simulate a successful AUB (HelloMoney) transaction read.
                $extractedAmount = 1500.00;
                $bankName = 'AUB'; // Asia United Bank (HelloMoney)
                $confidence = 98.5; 
                $referenceNumber = 'AUB-' . strtoupper(substr(md5(time()), 0, 8)); // Generate fake ref
                $date = date('Y-m-d'); // Today
                $time = date('H:i:s'); // Now
                
                $rawJson = json_encode([
                    'mock_status' => 'SUCCESS',
                    'note' => 'Generated by Intelligent Mock Mode (GCP Billing bypassed)',
                    'extracted_text' => "AUB HelloMoney\nSent ₱1,500.00\nRef No. $referenceNumber\nDate: $date $time"
                ]);
            } else {
                // Real Google Cloud Vision Logic would go here
                // Requires active Billing Account
                throw new Exception("Google Vision API is disabled. Please enable mock mode.");
            }

            // Save to ocr_results table
            $stmt = $this->pdo->prepare("
                INSERT INTO ocr_results (concern_id, extracted_amount, bank_name, confidence_score, reference_number, transaction_date, transaction_time, raw_json)
                VALUES (:cid, :amt, :bank, :conf, :ref, :tdate, :ttime, :raw)
            ");
            
            $stmt->execute([
                ':cid'   => $concernId,
                ':amt'   => $extractedAmount,
                ':bank'  => $bankName,
                ':conf'  => $confidence,
                ':ref'   => $referenceNumber,
                ':tdate' => $date,
                ':ttime' => $time,
                ':raw'   => $rawJson
            ]);

            $ocrResultId = $this->pdo->lastInsertId();

            // Update concern OCR status to Completed
            $stmtUpdate = $this->pdo->prepare("UPDATE payment_concerns SET ocr_status = 'Completed' WHERE concern_id = :cid");
            $stmtUpdate->execute([':cid' => $concernId]);

            return $ocrResultId;

        } catch (Exception $e) {
            // If OCR fails, update status to Failed
            $stmtUpdate = $this->pdo->prepare("UPDATE payment_concerns SET ocr_status = 'Failed', remarks = CONCAT(remarks, '\n[OCR Error] ', :err) WHERE concern_id = :cid");
            $stmtUpdate->execute([
                ':cid' => $concernId,
                ':err' => $e->getMessage()
            ]);
            return false;
        }
    }
}
