<?php
declare(strict_types=1);
final class OcrTechnicalStatusService{
 public function __construct(private readonly PDO $pdo){}
 public function load(array$config,array$credential):array{
  $tz=new DateTimeZone('Asia/Manila');$now=new DateTimeImmutable('now',$tz);$month=$now->format('Y-m-01');$usage=['available'=>true,'month'=>$month,'record_present'=>false,'configured_limit'=>(int)($config['monthly_limit']??900),'consumed'=>null,'reserved'=>null,'remaining'=>null,'provider_attempts'=>null,'successful'=>null,'failed'=>null,'cache_hits'=>null];$failures=[];$states=[];$stale=null;
  try{$q=$this->pdo->prepare('SELECT configured_limit,reserved_units,consumed_units,successful_units,failed_units FROM ocr_usage_months WHERE billing_month=?');$q->execute([$month]);if($row=$q->fetch(PDO::FETCH_ASSOC)){$limit=(int)$row['configured_limit'];$usage=array_merge($usage,['record_present'=>true,'configured_limit'=>$limit,'reserved'=>(int)$row['reserved_units'],'consumed'=>(int)$row['consumed_units'],'remaining'=>max(0,$limit-(int)$row['reserved_units']-(int)$row['consumed_units']),'successful'=>(int)$row['successful_units'],'failed'=>(int)$row['failed_units']]);}$q=$this->pdo->prepare('SELECT COUNT(*) FROM ocr_usage_ledger WHERE billing_month=? AND provider_called=1');$q->execute([$month]);$usage['provider_attempts']=(int)$q->fetchColumn();$q=$this->pdo->prepare("SELECT COUNT(*) FROM ocr_usage_ledger WHERE billing_month=? AND lifecycle_state='CACHE_HIT'");$q->execute([$month]);$usage['cache_hits']=(int)$q->fetchColumn();$q=$this->pdo->prepare('SELECT lifecycle_state,COUNT(*) total FROM ocr_usage_ledger WHERE billing_month=? GROUP BY lifecycle_state ORDER BY lifecycle_state');$q->execute([$month]);$states=$q->fetchAll(PDO::FETCH_ASSOC);$q=$this->pdo->prepare("SELECT COALESCE(failure_category,'UNCLASSIFIED') category,COUNT(*) total FROM ocr_usage_ledger WHERE billing_month=? AND lifecycle_state IN ('FAILED','RELEASED','REJECTED_LIMIT') GROUP BY COALESCE(failure_category,'UNCLASSIFIED') ORDER BY total DESC,category LIMIT 10");$q->execute([$month]);$failures=$q->fetchAll(PDO::FETCH_ASSOC);$cutoff=$now->modify('-15 minutes')->format('Y-m-d H:i:s');$q=$this->pdo->prepare("SELECT COUNT(*) FROM ocr_usage_ledger WHERE (lifecycle_state='RESERVED' AND reserved_at<?) OR (lifecycle_state='PROVIDER_CALLED' AND provider_called_at<? AND completed_at IS NULL)");$q->execute([$cutoff,$cutoff]);$stale=(int)$q->fetchColumn();}
  catch(Throwable$e){error_log('OCR technical monitoring unavailable: '.get_class($e));$usage['available']=false;$usage['provider_attempts']=$usage['cache_hits']=null;$failures=[];$states=[];$stale=null;}
  return['configuration'=>['enabled'=>(bool)($config['enabled']??false),'provider'=>'Google Cloud Vision','feature'=>'DOCUMENT_TEXT_DETECTION','project_configured'=>(string)($config['project_id']??'')!=='','credential_status'=>$credential['status']??'NOT_CONFIGURED','credential_protected'=>(bool)($credential['protected_location']??false)],'diagnostic'=>['last_status'=>$config['last_test_status']??null,'last_successful'=>$config['last_successful_test']??null,'last_failed'=>$config['last_failed_test']??null,'authentication_state'=>$config['last_test_authentication']??null,'error_category'=>$config['last_test_error_category']??null,'provider_capability'=>'UNVERIFIED','actual_ocr_processing'=>'UNVERIFIED'],'usage'=>$usage,'lifecycle_states'=>$states,'failure_categories'=>$failures,'stale_incomplete'=>$stale];
 }
}
