<?php
declare(strict_types=1);
require_once __DIR__.'/AccountingReportingPeriod.php';
final class PaymentAdminReportingService
{
 private PDO $pdo;public function __construct(PDO $pdo){$this->pdo=$pdo;}
 private function section(array &$d,string $key,callable $fn):void{try{$d[$key]=$fn();$d['section_status'][$key]=$d[$key]===[]?'no_data':'ok';}catch(Throwable $e){error_log('Payment Admin dashboard ['.$key.']: '.$e->getMessage());$d[$key]=null;$d['section_status'][$key]='error';}}
 public function load(array $input=[]):array
 {
  $r=AccountingReportingPeriod::fromRequest($input);$start=AccountingReportingPeriod::sql($r['start_at']);$end=AccountingReportingPeriod::sql($r['end_exclusive']);$d=['ok'=>true,'generated_at'=>(new DateTimeImmutable('now',new DateTimeZone(AccountingReportingPeriod::TIMEZONE)))->format(DATE_ATOM),'scope'=>['period'=>$r['period'],'period_month'=>$r['period_month'],'period_year'=>$r['period_year'],'period_label'=>$r['period_label'],'timezone'=>AccountingReportingPeriod::TIMEZONE,'start_at'=>$start,'end_exclusive'=>$end,'comparison_label'=>$r['comparison_label']],'section_status'=>[]];
  $this->section($d,'available_period_years',function(){ $q=$this->pdo->query("SELECT report_year FROM (SELECT YEAR(created_at) report_year FROM payments WHERE transaction_type='Online' UNION SELECT YEAR(verified_at) report_year FROM payments WHERE transaction_type='Online' AND verified_at IS NOT NULL) reporting_years WHERE report_year IS NOT NULL GROUP BY report_year ORDER BY report_year DESC");$years=array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN));$currentYear=(int)(new DateTimeImmutable('now',new DateTimeZone(AccountingReportingPeriod::TIMEZONE)))->format('Y');if(!in_array($currentYear,$years,true))$years[]=$currentYear;rsort($years,SORT_NUMERIC);return$years;});
  $this->section($d,'kpis',function()use($start,$end){$q=$this->pdo->prepare("SELECT COUNT(*) total_count,SUM(payment_status='Pending') pending_count,SUM(payment_status='Failed') failed_count,SUM(payment_status='Expired') expired_count,SUM(payment_status='Cancelled') cancelled_count,SUM(payment_status='Rejected') rejected_count FROM payments WHERE transaction_type='Online' AND created_at>=? AND created_at<?");$q->execute([$start,$end]);$r=$q->fetch(PDO::FETCH_ASSOC)?:[];$a=$this->pdo->prepare("SELECT COALESCE(SUM(x.applied_amount),0) amount,COUNT(DISTINCT p.payment_id) count FROM payments p JOIN (SELECT payment_id,SUM(allocated_amount) applied_amount FROM payment_allocations GROUP BY payment_id) x ON x.payment_id=p.payment_id WHERE p.transaction_type='Online' AND p.payment_status='Verified' AND p.gateway_environment='live' AND p.verified_at>=? AND p.verified_at<?");$a->execute([$start,$end]);$v=$a->fetch(PDO::FETCH_ASSOC)?:[];$vc=$this->pdo->prepare("SELECT COUNT(*) FROM payments WHERE transaction_type='Online' AND payment_status='Verified' AND gateway_environment='live' AND verified_at>=? AND verified_at<?");$vc->execute([$start,$end]);return['online_count'=>(int)($r['total_count']??0),'verified_count'=>(int)$vc->fetchColumn(),'pending_count'=>(int)($r['pending_count']??0),'failed_count'=>(int)($r['failed_count']??0),'expired_count'=>(int)($r['expired_count']??0),'cancelled_count'=>(int)($r['cancelled_count']??0),'rejected_count'=>(int)($r['rejected_count']??0),'online_amount'=>(float)($v['amount']??0),'online_amount_count'=>(int)($v['count']??0)];});
  $this->section($d,'trend',function()use($r,$start,$end){$unit=$r['period'];$step=match($unit){'today'=>'hour','year'=>'month',default=>'day'};$partial=$r['end_exclusive']->format('H:i:s')!=='00:00:00';$completeMonth=$unit==='month'&&!$r['is_current_range'];$completeYear=$unit==='year'&&!$r['is_current_range'];$n=match($unit){'today'=>(int)$r['end_exclusive']->format('G')+($partial?1:0),'week'=>(int)$r['end_exclusive']->format('N')-($partial?0:1),'month'=>$completeMonth?(int)$r['start_at']->format('t'):(int)$r['end_exclusive']->format('j')-($partial?0:1),default=>$completeYear?12:(int)$r['end_exclusive']->format('n')-(($r['end_exclusive']->format('m-d')==='01-01'&&!$partial)?1:0)};$labels=[];$cursor=$r['start_at'];$monthKeys=[];for($i=0;$i<max(0,$n);$i++){$labels[]=$cursor->format($step==='hour'?'g A':($step==='month'?'M':'M j'));$monthKeys[]=$cursor->format('Y-m');$cursor=$cursor->modify('+1 '.$step);} $expr=match($step){'hour'=>"HOUR(p.verified_at)",'month'=>"DATE_FORMAT(p.verified_at,'%Y-%m')",'day'=>'DATEDIFF(DATE(p.verified_at),DATE(?))'};$params=[];if($step==='day')$params[]=AccountingReportingPeriod::sql($r['start_at']);$params[]=$start;$params[]=$end;$sql="SELECT {$expr} bucket,SUM(x.applied_amount) amount FROM payments p JOIN (SELECT payment_id,SUM(allocated_amount) applied_amount FROM payment_allocations GROUP BY payment_id) x ON x.payment_id=p.payment_id WHERE p.transaction_type='Online' AND p.payment_status='Verified' AND p.gateway_environment='live' AND p.verified_at>=? AND p.verified_at<? GROUP BY bucket";$q=$this->pdo->prepare($sql);$q->execute($params);$values=array_fill(0,count($labels),0.0);foreach($q->fetchAll(PDO::FETCH_ASSOC)as$row){$idx=$step==='month'?array_search((string)$row['bucket'],$monthKeys,true):(int)$row['bucket'];if($idx!==false&&isset($values[$idx]))$values[$idx]=(float)$row['amount'];}return['labels'=>$labels,'current'=>$values,'prior'=>[],'comparison_label'=>null];});
  $this->section($d,'channel_breakdown',function()use($start,$end){$q=$this->pdo->prepare("SELECT p.payment_channel label,LOWER(REPLACE(p.payment_channel,' ','')) channel_code,COALESCE(SUM(x.applied_amount),0) amount,COUNT(DISTINCT p.payment_id) payment_count FROM payments p JOIN (SELECT payment_id,SUM(allocated_amount) applied_amount FROM payment_allocations GROUP BY payment_id) x ON x.payment_id=p.payment_id WHERE p.transaction_type='Online' AND p.payment_status='Verified' AND p.gateway_environment='live' AND p.verified_at>=? AND p.verified_at<? GROUP BY p.payment_channel ORDER BY amount DESC");$q->execute([$start,$end]);return$q->fetchAll(PDO::FETCH_ASSOC);});
  $this->section($d,'online_status',function()use($start,$end){$q=$this->pdo->prepare("SELECT CASE WHEN payment_status IN ('Verified','Pending','Failed','Expired','Cancelled','Rejected') THEN payment_status ELSE 'Unknown' END status,COUNT(*) count FROM payments WHERE transaction_type='Online' AND created_at>=? AND created_at<? GROUP BY status ORDER BY status");$q->execute([$start,$end]);return$q->fetchAll(PDO::FETCH_ASSOC);});
  $this->section($d,'recent_activity',function()use($start,$end){$q=$this->pdo->prepare("SELECT p.payment_id,p.verified_at,p.created_at,p.reference_number,p.receipt_number,s.full_name,s.student_number,p.payment_channel,p.gateway_environment,CASE WHEN p.payment_status IN ('Verified','Pending','Failed','Expired','Cancelled','Rejected') THEN p.payment_status ELSE 'Unknown' END payment_status,p.amount attempted_amount,COALESCE(a.applied_amount,0) applied_amount FROM payments p LEFT JOIN students s ON s.student_id=p.student_id LEFT JOIN (SELECT payment_id,SUM(allocated_amount) applied_amount FROM payment_allocations GROUP BY payment_id) a ON a.payment_id=p.payment_id WHERE p.transaction_type='Online' AND ((p.payment_status='Verified' AND p.verified_at>=? AND p.verified_at<?) OR (COALESCE(p.payment_status,'')<>'Verified' AND p.created_at>=? AND p.created_at<?)) ORDER BY COALESCE(p.verified_at,p.created_at) DESC,p.payment_id DESC LIMIT 12");$q->execute([$start,$end,$start,$end]);return$q->fetchAll(PDO::FETCH_ASSOC);});
  $this->section($d,'configuration',function(){ $q=$this->pdo->query("SELECT setting_key,setting_value FROM payment_gateway_settings WHERE setting_key IN ('gateway_mode','live_channel_gcash','live_channel_maya','live_channel_card','live_channel_qrph','test_channel_gcash','test_channel_maya','test_channel_card','test_channel_qrph')");$s=[];foreach($q->fetchAll(PDO::FETCH_ASSOC)as$x)$s[$x['setting_key']]=$x['setting_value'];$mode=($s['gateway_mode']??'test')==='live'?'live':'test';$channels=[];foreach(['gcash'=>'GCash','maya'=>'Maya','card'=>'Card','qrph'=>'QRPh']as$k=>$name){$configured=($s[$mode.'_channel_'.$k]??'0')==='1';$allowed=$mode!=='live'||$k==='qrph';$channels[]=['code'=>$k,'name'=>$name,'configured'=>$configured,'available_by_config'=>$configured&&$allowed,'policy_allowed'=>$allowed];}return['gateway_mode'=>$mode,'channels'=>$channels];});
  return$d;
 }
}
