<?php
declare(strict_types=1);

/**
 * Payment-side REST boundary for authoritative enrollment cohorts.
 * It deliberately has no knowledge of Registrar database tables.
 */
final class RegistrarCohortException extends RuntimeException
{
    public function __construct(public readonly string $errorCode, string $message)
    {
        parent::__construct($message);
    }
}

final class RegistrarCohortClient
{
    private const TIMEOUT_SECONDS = 8;

    public function configured(): bool
    {
        return $this->endpoint('REGISTRAR_ACTIVE_CONTEXT_ENDPOINT') !== ''
            && $this->endpoint('REGISTRAR_COHORTS_ENDPOINT') !== ''
            && $this->endpoint('REGISTRAR_COHORT_STUDENTS_ENDPOINT') !== '';
    }

    /** @return array{academic_year:string,semester:string,enrollment_status:string} */
    public function getActiveEnrollmentContext(): array
    {
        $payload = $this->get('REGISTRAR_ACTIVE_CONTEXT_ENDPOINT');
        $data = $this->data($payload);
        if (isset($data[0]) && is_array($data[0])) {
            if (count($data) !== 1) throw new RegistrarCohortException('ACTIVE_CONTEXT_AMBIGUOUS', 'Registrar returned multiple active enrollment contexts.');
            $data = $data[0];
        }
        if (!is_array($data)) throw new RegistrarCohortException('COHORT_RESPONSE_INVALID', 'Registrar active-context response is invalid.');
        $context = [
            'academic_year' => trim((string)($data['academic_year'] ?? '')),
            'semester' => trim((string)($data['semester'] ?? '')),
            'enrollment_status' => trim((string)($data['enrollment_status'] ?? '')),
        ];
        if (!preg_match('/^\d{4}-\d{4}$/', $context['academic_year'])
            || !in_array($context['semester'], ['1st', '2nd', 'Summer'], true)
            || $context['enrollment_status'] !== 'Enrolled') {
            throw new RegistrarCohortException('COHORT_RESPONSE_INVALID', 'Registrar active-context response is incomplete.');
        }
        return $context;
    }

    /** @param array{academic_year:string,semester:string,enrollment_status:string} $context @return list<array{cohort_id:string,program_code:string,year_level:string,student_count:int}> */
    public function listAvailableCohorts(array $context): array
    {
        $data = $this->data($this->get('REGISTRAR_COHORTS_ENDPOINT', $context));
        $rows = is_array($data['cohorts'] ?? null) ? $data['cohorts'] : $data;
        if (!is_array($rows) || !array_is_list($rows)) throw new RegistrarCohortException('COHORT_RESPONSE_INVALID', 'Registrar cohort-list response is invalid.');
        $out = [];
        foreach ($rows as $row) {
            if (!is_array($row)) throw new RegistrarCohortException('COHORT_RESPONSE_INVALID', 'Registrar returned an invalid cohort.');
            $program = trim((string)($row['program_code'] ?? ''));
            $year = trim((string)($row['year_level'] ?? ''));
            // A documented canonical fallback is generated by Payment, never accepted from the browser.
            $id = trim((string)($row['cohort_id'] ?? ''));
            if ($id === '') $id = 'fallback:' . hash('sha256', $context['academic_year'].'|'.$context['semester'].'|'.$program.'|'.$year);
            if ($program === '' || $year === '') throw new RegistrarCohortException('COHORT_RESPONSE_INVALID', 'Registrar cohort is missing program or year level.');
            $out[$id] = ['cohort_id'=>$id, 'program_code'=>$program, 'year_level'=>$year, 'student_count'=>max(0, (int)($row['student_count'] ?? 0))];
        }
        return array_values($out);
    }

    /** @param array{academic_year:string,semester:string,enrollment_status:string} $context @return list<array<string,string>> */
    public function getCohortStudents(array $context, string $cohortId): array
    {
        if ($cohortId === '') throw new RegistrarCohortException('COHORT_RESPONSE_INVALID', 'A Registrar cohort is required.');
        $data = $this->data($this->get('REGISTRAR_COHORT_STUDENTS_ENDPOINT', array_merge($context, ['cohort_id'=>$cohortId])));
        $rows = is_array($data['students'] ?? null) ? $data['students'] : $data;
        if (!is_array($rows) || !array_is_list($rows)) throw new RegistrarCohortException('COHORT_RESPONSE_INVALID', 'Registrar student-cohort response is invalid.');
        return $rows;
    }

    private function endpoint(string $name): string
    {
        $value = trim((string)getenv($name));
        if ($value !== '') return $value;
        $base = rtrim((string)getenv('REGISTRAR_API_BASE_URL'), '/');
        return $base === '' ? '' : $base . match ($name) {
            'REGISTRAR_ACTIVE_CONTEXT_ENDPOINT' => '/enrollment/active-context',
            'REGISTRAR_COHORTS_ENDPOINT' => '/enrollment/cohorts',
            default => '/enrollment/cohort-students',
        };
    }

    /** @return array<string,mixed> */
    private function get(string $endpointName, array $query=[]): array
    {
        if (!$this->configured()) throw new RegistrarCohortException('COHORT_SOURCE_UNAVAILABLE', 'Authoritative Enrollment/Registrar cohort service is not currently configured.');
        $url = $this->endpoint($endpointName);
        $url .= (str_contains($url, '?') ? '&' : '?') . http_build_query($query);
        $headers = "Accept: application/json\r\n";
        $token = trim((string)getenv('REGISTRAR_API_TOKEN'));
        if ($token !== '') $headers .= "Authorization: Bearer {$token}\r\n";
        $response = @file_get_contents($url, false, stream_context_create(['http'=>['method'=>'GET','timeout'=>self::TIMEOUT_SECONDS,'ignore_errors'=>true,'header'=>$headers]]));
        if ($response === false || $response === '') throw new RegistrarCohortException('COHORT_SOURCE_UNAVAILABLE', 'Authoritative Enrollment/Registrar cohort service is unavailable.');
        try { $payload = json_decode($response, true, 512, JSON_THROW_ON_ERROR); }
        catch (JsonException) { throw new RegistrarCohortException('COHORT_RESPONSE_INVALID', 'Registrar returned malformed JSON.'); }
        if (!is_array($payload) || (array_key_exists('success', $payload) && !$payload['success'])) throw new RegistrarCohortException('COHORT_RESPONSE_INVALID', 'Registrar rejected the cohort request.');
        return $payload;
    }

    private function data(array $payload): mixed { return $payload['data'] ?? $payload; }
}
