<?php
require_once __DIR__.'/../../../../config/config.php';require_once ROOT_PATH.'/includes/authentication.php';require_once __DIR__.'/../../database/db_connect.php';require_once __DIR__.'/../../includes/AccountingReportingPageService.php';requireAuth();requirePaymentPermission('payment.analytics');
$pageTitle='Accounting Dashboard';$activeModule='payment';$activePage='accounting/dashboard';$breadcrumbs=[['label'=>'Payment Management','url'=>BASE_URL.'/modules/payment/index.php'],['label'=>'Dashboard','url'=>null]];$role=getCurrentUserRoleKey();$svc=new AccountingReportingPageService($pdo);try{$d=$svc->load($_GET,true);}catch(Throwable $e){$d=null;}$options=$d['filter_options']??['terms'=>[],'channels'=>[],'categories'=>[]];require_once ROOT_PATH.'/includes/breadcrumbs.php';require_once ROOT_PATH.'/includes/layout-start.php';
?>
<?php renderBreadcrumbs($breadcrumbs); ?>
<div class="container-fluid py-4">
 <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-3"><div><h1 class="h3 mb-1"><i class="ti ti-chart-pie text-primary me-2" aria-hidden="true"></i>Accounting Dashboard</h1><p class="text-muted mb-0">Payment collections and account summary</p></div><small id="lastUpdated" class="text-muted">Loading dashboard data...</small></div>
 <form id="dashboardFilters" class="card border-0 shadow-sm mb-3"><div class="card-body"><div class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label" for="accountingAcademicYear">Academic Year</label><select id="accountingAcademicYear" class="form-select" name="academic_year"><?php foreach($options['terms'] as $t):?><option value="<?=htmlspecialchars($t['academic_year'])?>" <?=($d['scope']['academic_year']??'')===$t['academic_year']?'selected':''?>><?=htmlspecialchars($t['academic_year'])?></option><?php endforeach?></select></div><div class="col-md-3"><label class="form-label" for="accountingSemester">Semester</label><select id="accountingSemester" class="form-select" name="semester"><?php foreach(['1st','2nd','Summer'] as $semester):?><option <?=($d['scope']['semester']??'')===$semester?'selected':''?>><?=$semester?></option><?php endforeach?></select></div><div class="col-md-3"><label class="form-label" for="accountingPeriod">Collection Period</label><select id="accountingPeriod" class="form-select" name="period"><?php foreach(['today'=>'Today','week'=>'Week','month'=>'Month','year'=>'Year'] as $v=>$label):?><option value="<?=$v?>" <?=($d['scope']['period']??'today')===$v?'selected':''?>><?=$label?></option><?php endforeach?></select></div><div class="col-md-2"><button class="btn btn-primary w-100"><i class="ti ti-filter me-1" aria-hidden="true"></i>Apply</button></div></div></div></form>
 <div id="dashState" class="small text-muted mb-3" role="status">Loading dashboard data...</div><div id="integrityAlerts"></div><div id="dashboardContent" class="d-none">
  <div class="row g-3 mb-4" id="dashKpis"></div>
  <div class="row g-3 mb-4"><div class="col-xl-8"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5"><i class="ti ti-chart-line text-primary me-2" aria-hidden="true"></i>Collection Trend</h2><div style="height:300px"><canvas id="collectionTrendChart" aria-label="Collection trend"></canvas></div><div id="trendState" class="small text-muted" role="status"></div></div></div></div><div class="col-xl-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5"><i class="ti ti-chart-donut text-primary me-2" aria-hidden="true"></i>Payment Methods</h2><div style="height:270px"><canvas id="paymentMethodsChart" aria-label="Payment methods"></canvas></div><div id="methodsState" class="small text-muted" role="status"></div></div></div></div></div>
  <div class="row g-3 mb-4"><div class="col-lg-8"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5"><i class="ti ti-category text-primary me-2" aria-hidden="true"></i>Collections by Fee Category</h2><div style="height:300px"><canvas id="feeCategoryChart" aria-label="Collections by fee category"></canvas></div><div id="categoryState" class="small text-muted" role="status"></div></div></div></div><div class="col-lg-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5"><i class="ti ti-world-dollar text-primary me-2" aria-hidden="true"></i>Online Payment Summary</h2><p class="small text-muted">Attempts by actual status; Live verified allocations are shown in Online Payments.</p><div id="onlineSummary"></div></div></div></div></div>
  <div class="card border-0 shadow-sm mb-4"><div class="card-body"><div class="d-flex flex-wrap justify-content-between align-items-start gap-2 mb-3"><div><h2 class="h5 mb-1"><i class="ti ti-receipt text-primary me-2" aria-hidden="true"></i>Recent Payments</h2><p class="small text-muted mb-0">One row per payment; amount is the applied allocation total.</p></div></div><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Date &amp; Time</th><th>Student</th><th>Reference No.</th><th>Payment Method</th><th class="text-end">Applied Amount</th><th>Status</th></tr></thead><tbody id="recentRows"><tr><td colspan="6" class="text-center text-muted py-4">Loading payments...</td></tr></tbody></table></div></div></div>
 </div>
 <div class="card mb-4"><div class="card-body"><h2 class="h5">Quick Actions</h2><div class="d-flex flex-wrap gap-2"><?php foreach([['payment.fee_setup','Fee Setup','fee-setup-configuration.php'],['payment.billing','Billing & SOA','student-billing-invoicing.php'],['payment.ledger','Payment Ledger','payment-history-ledger-system.php'],['payment.concern_review','Payment Concerns','payment-concern-portal.php'],['payment.concern_review','Bank Reconciliation','bank-reconciliation.php']] as [$permission,$label,$path]):if(paymentRoleAllowsPermission($role,$permission)):?><a class="btn btn-outline-primary" href="<?=BASE_URL?>/modules/payment/pages/accounting/<?=rawurlencode($path)?>"><?=htmlspecialchars($label)?></a><?php endif;endforeach?><a class="btn btn-outline-secondary" href="<?=BASE_URL?>/modules/payment/pages/accounting/collection-reporting-analytics.php">Collection Reporting</a></div></div></div>
</div>
<script>window.ACCOUNTING_DASHBOARD_API='<?=BASE_URL?>/modules/payment/api/dashboard-data.php';</script><script src="<?=BASE_URL?>/modules/payment/assets/js/accounting-dashboard.js?v=2"></script>
<?php require_once ROOT_PATH.'/includes/layout-end.php'; ?>
