<?php
declare(strict_types=1);
require_once __DIR__.'/../../../../config/config.php';require_once ROOT_PATH.'/includes/authentication.php';requireAuth();requirePaymentPermission('billing.individual.process');
$pageTitle='Accounting Officer Dashboard';$activeModule='payment';$activePage='accounting/dashboard';$breadcrumbs=[['label'=>'Payment Management','url'=>BASE_URL.'/modules/payment/index.php'],['label'=>'Accounting Officer Dashboard','url'=>null]];require_once ROOT_PATH.'/includes/breadcrumbs.php';require_once ROOT_PATH.'/includes/layout-start.php';
?>
<?php renderBreadcrumbs($breadcrumbs); ?>
<style>
 #officerDashboard{color:var(--sms-text)}#officerDashboard .card{background:var(--sms-surface);color:var(--sms-text);border-color:var(--sms-border-soft)!important}#officerDashboard .text-muted{color:var(--sms-text-muted)!important}#officerDashboard .officer-kpi{transition:transform .16s ease,box-shadow .16s ease;color:var(--sms-text)!important}#officerDashboard .officer-kpi:hover{transform:translateY(-2px);box-shadow:var(--sms-shadow-md)!important}.officer-kpi-icon,.officer-action-icon{display:inline-grid;place-items:center;width:2.55rem;height:2.55rem;border-radius:.75rem;background:var(--sms-primary-xlight);color:var(--sms-primary);font-size:1.05rem}.officer-action-icon{width:2rem;height:2rem;border-radius:.55rem}.officer-kpi-value{color:var(--sms-heading);font-weight:800}.officer-quick-action{display:inline-flex;align-items:center;gap:.55rem}.officer-quick-action:hover{color:#fff!important}
</style>
<main class="container-fluid py-4" id="officerDashboard" data-api="<?= htmlspecialchars(BASE_URL.'/modules/payment/api/accounting/officer-dashboard.php',ENT_QUOTES,'UTF-8') ?>" data-billing-url="<?= htmlspecialchars(BASE_URL.'/modules/payment/pages/accounting/student-billing-invoicing.php',ENT_QUOTES,'UTF-8') ?>" data-concerns-url="<?= htmlspecialchars(BASE_URL.'/modules/payment/pages/accounting/payment-concern-portal.php',ENT_QUOTES,'UTF-8') ?>" data-aub-url="<?= htmlspecialchars(BASE_URL.'/modules/payment/pages/accounting/bank-reconciliation.php',ENT_QUOTES,'UTF-8') ?>">
 <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><h1 class="h3 mb-1">Accounting Officer Dashboard</h1><p class="text-muted mb-0">Daily billing workload, managed-run actions, and operational exceptions.</p></div><small id="officerDashboardUpdated" class="text-muted"></small></div>
 <form id="officerDashboardFilters" class="card border-0 shadow-sm mb-4"><div class="card-body"><div class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label" for="officerAcademicYear">Academic Year</label><select id="officerAcademicYear" class="form-select" name="academic_year"></select></div><div class="col-md-3"><label class="form-label" for="officerSemester">Semester</label><select id="officerSemester" class="form-select" name="semester"><option value="1st">1st</option><option value="2nd">2nd</option><option value="Summer">Summer</option></select></div><div class="col-md-auto"><button class="btn btn-outline-primary">Apply</button></div></div></div></form>
 <div id="officerDashboardState" class="small text-muted mb-3" role="status">Loading operational dashboard…</div>
 <section class="row g-3 mb-4" id="officerKpis"></section>
 <section class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5 mb-3">Quick Actions</h2><div class="d-flex flex-wrap gap-2"><a class="btn btn-primary officer-quick-action" data-quick="individual"><span class="officer-action-icon bg-white text-primary"><i class="fas fa-file-invoice"></i></span>Individual Billing</a><a class="btn btn-primary officer-quick-action" data-quick="bulk"><span class="officer-action-icon bg-white text-primary"><i class="fas fa-layer-group"></i></span>Create Bulk Assessment</a><a class="btn btn-outline-primary officer-quick-action" data-quick="concerns"><span class="officer-action-icon"><i class="fas fa-triangle-exclamation"></i></span>Review Payment Concerns</a><a class="btn btn-outline-primary officer-quick-action" data-quick="aub"><span class="officer-action-icon"><i class="fas fa-building-columns"></i></span>AUB Reconciliation</a></div></div></section>
 <section class="row g-3 mb-4"><div class="col-xl-7"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">Successful Managed Assessments — Last 7 Days</h2><div id="assessmentTrendEmpty" class="text-muted py-5 text-center">Loading activity…</div><div id="assessmentTrendWrap" class="d-none" style="height:280px"><canvas id="assessmentTrendChart"></canvas></div></div></div></div><div class="col-xl-5"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">Current Bulk Assignment Outcomes</h2><div id="outcomesEmpty" class="text-muted py-5 text-center">Loading outcomes…</div><div id="outcomesWrap" class="d-none" style="height:280px"><canvas id="outcomesChart"></canvas></div></div></div></div></section>
 <section class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5 mb-3">Bulk Billing Work Queue</h2><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Run</th><th>Term</th><th>Cohort</th><th>Students</th><th>Status</th><th class="text-end">Action</th></tr></thead><tbody id="workQueueRows"><tr><td colspan="6" class="text-center text-muted py-4">Loading work queue…</td></tr></tbody></table></div></div></section>
 <section class="row g-3 mb-4"><div class="col-lg-5"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5 mb-3">Attention Required</h2><div id="attentionRequired"></div></div></div></div><div class="col-lg-7"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5 mb-3">Recent Operational Activity</h2><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Time</th><th>Activity</th><th>Result</th></tr></thead><tbody id="recentOperationalRows"><tr><td colspan="3" class="text-center text-muted py-4">Loading recent activity…</td></tr></tbody></table></div></div></div></div></section>
</main>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script src="<?= BASE_URL ?>/modules/payment/assets/js/accounting-officer-dashboard.js?v=1"></script>
<?php require_once ROOT_PATH.'/includes/layout-end.php'; ?>
