<?php
require_once __DIR__.'/../../../../config/config.php';require_once ROOT_PATH.'/includes/authentication.php';require_once __DIR__.'/../../database/db_connect.php';require_once __DIR__.'/../../includes/AccountingReportingPageService.php';requireAuth();requirePaymentPermission('payment.analytics');
$pageTitle='Accounting Dashboard';$activeModule='payment';$activePage='accounting/dashboard';$breadcrumbs=[['label'=>'Payment Management','url'=>BASE_URL.'/modules/payment/index.php'],['label'=>'Dashboard','url'=>null]];$role=getCurrentUserRoleKey();$svc=new AccountingReportingPageService($pdo);try{$d=$svc->load($_GET,true);}catch(Throwable $e){$d=null;$pageError=$e->getMessage();}$options=$d['filter_options']??['terms'=>[],'channels'=>[],'categories'=>[]];require_once ROOT_PATH.'/includes/breadcrumbs.php';require_once ROOT_PATH.'/includes/layout-start.php';
?>
<div class="d-flex justify-content-between align-items-start mb-4"><div><h1 class="h3">Accounting Dashboard</h1><p class="text-muted">Academic financial snapshots and official allocation collections.</p></div></div>
<form id="dashboardFilters" class="card card-body mb-4"><div class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label">Academic Year</label><select class="form-select" name="academic_year"><?php foreach($options['terms'] as $t):?><option value="<?=htmlspecialchars($t['academic_year'])?>" <?=($d['scope']['academic_year']??'')===$t['academic_year']?'selected':''?>><?=htmlspecialchars($t['academic_year'])?></option><?php endforeach?></select></div><div class="col-md-3"><label class="form-label">Semester</label><select class="form-select" name="semester"><option>1st</option><option>2nd</option><option>Summer</option></select></div><div class="col-md-3"><label class="form-label">Collection period</label><select class="form-select" name="period"><option value="today">Today</option><option value="week">Week</option><option value="month">Month</option><option value="year">Year</option></select></div><div class="col-md-2"><button class="btn btn-primary w-100">Apply</button></div></div></form>
<div id="dashState" class="alert alert-info" role="status">Loading?</div><div id="integrityAlerts"></div><div id="dashboardContent" class="d-none">
<div class="row g-3 mb-4" id="dashKpis"></div><div class="row g-3 mb-4"><div class="col-xl-8"><div class="card h-100"><div class="card-body"><h2 class="h5">Official Collection Trend</h2><div id="trendRows" class="table-responsive"></div></div></div></div><div class="col-xl-4"><div class="card h-100"><div class="card-body"><h2 class="h5">Needs Attention</h2><div id="attentionList"></div></div></div></div></div>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="card h-100"><div class="card-body"><h2 class="h5">Fee Category Collections</h2><div id="categoryRows"></div></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body"><h2 class="h5">Payment Channel Collections</h2><div id="channelRows"></div></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body"><h2 class="h5">Online Payment Status</h2><div id="onlineRows"></div></div></div></div></div>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="card"><div class="card-body"><h2 class="h6">Payment Concerns / OCR</h2><div id="concernRows"></div></div></div></div><div class="col-md-4"><div class="card"><div class="card-body"><h2 class="h6">Bank Reconciliation</h2><div id="bankRows"></div></div></div></div><div class="col-md-4"><div class="card"><div class="card-body"><h2 class="h6">Billing Activity</h2><div id="billingRows"></div></div></div></div></div>
<div class="card mb-4"><div class="card-body"><h2 class="h5">Recent Official Collections</h2><div class="table-responsive"><table class="table"><thead><tr><th>Verified at</th><th>OR / Reference</th><th>Student</th><th>Type</th><th>Channel</th><th class="text-end">Applied</th></tr></thead><tbody id="recentRows"></tbody></table></div></div></div>
</div>
<div class="card mb-4"><div class="card-body"><h2 class="h5">Quick Actions</h2><div class="d-flex flex-wrap gap-2"><?php foreach([['payment.fee_setup','Fee Setup','fee-setup-configuration.php'],['payment.billing','Billing & SOA','student-billing-invoicing.php'],['payment.ledger','Payment Ledger','payment-history-ledger-system.php'],['payment.concern_review','Payment Concerns','payment-concern-portal.php'],['payment.concern_review','Bank Reconciliation','bank-reconciliation.php']] as [$permission,$label,$path]):if(paymentRoleAllowsPermission($role,$permission)):?><a class="btn btn-outline-primary" href="<?=BASE_URL?>/modules/payment/pages/accounting/<?=rawurlencode($path)?>"><?=htmlspecialchars($label)?></a><?php endif;endforeach?><a class="btn btn-outline-secondary" href="<?=BASE_URL?>/modules/payment/pages/accounting/collection-reporting-analytics.php">Collection Reporting</a></div></div></div>
<script>window.ACCOUNTING_DASHBOARD_API='<?=BASE_URL?>/modules/payment/api/dashboard-data.php';</script><script src="<?=BASE_URL?>/modules/payment/assets/js/accounting-live-online-kpi.js"></script><script src="<?=BASE_URL?>/modules/payment/assets/js/accounting-dashboard.js"></script>
