<?php
declare(strict_types=1);
require_once __DIR__ . '/../../../../config/config.php';
require_once ROOT_PATH . '/includes/authentication.php';
requireAuth();
requirePaymentPermission('payment_users.view');
$pageTitle = 'Payment Personnel Management';
$activeModule = 'payment';
$activePage = 'mis_admin/payment-user-management';
$breadcrumbs = [['label' => 'Payment Management', 'url' => BASE_URL . '/modules/payment/index.php'], ['label' => 'MIS Admin', 'url' => null], ['label' => 'Payment Personnel', 'url' => null]];
require_once ROOT_PATH . '/includes/breadcrumbs.php';
require_once ROOT_PATH . '/includes/layout-start.php';
renderBreadcrumbs($breadcrumbs);
?>
<main class="container-fluid py-4" id="accountingUsersApp"
 data-api="<?= htmlspecialchars(BASE_URL . '/modules/payment/api/mis_admin/payment-users.php', ENT_QUOTES, 'UTF-8') ?>"
 data-csrf="<?= htmlspecialchars(csrfToken(), ENT_QUOTES, 'UTF-8') ?>"
 data-can-create="<?= paymentRoleAllowsPermission(getCurrentUserRoleKey(), 'payment_users.create') ? '1' : '0' ?>"
 data-can-update="<?= paymentRoleAllowsPermission(getCurrentUserRoleKey(), 'payment_users.update') ? '1' : '0' ?>"
 data-can-assign-role="<?= paymentRoleAllowsPermission(getCurrentUserRoleKey(), 'payment_users.role.assign') ? '1' : '0' ?>"
 data-can-activate="<?= paymentRoleAllowsPermission(getCurrentUserRoleKey(), 'payment_users.activate') ? '1' : '0' ?>"
 data-can-deactivate="<?= paymentRoleAllowsPermission(getCurrentUserRoleKey(), 'payment_users.deactivate') ? '1' : '0' ?>"
 data-can-unlock="<?= paymentRoleAllowsPermission(getCurrentUserRoleKey(), 'payment_users.unlock') ? '1' : '0' ?>"
 data-can-reset-password="<?= paymentRoleAllowsPermission(getCurrentUserRoleKey(), 'payment_users.password.reset') ? '1' : '0' ?>">
 <div class="d-flex justify-content-between align-items-start gap-3 mb-4"><div><h1 class="h3 mb-1">Payment Personnel Management</h1><p class="text-muted mb-0">Manage Accounting Admin, Accounting Officer, and Cashier accounts only. MIS Admin and all non-Payment accounts are outside this portal.</p></div><?php if (paymentRoleAllowsPermission(getCurrentUserRoleKey(), 'payment_users.create')): ?><button class="btn btn-primary" id="newOfficer">Add Payment User</button><?php endif; ?></div>
 <div id="accountingUsersMessage" aria-live="polite"></div>
 <section class="card border-0 shadow-sm"><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th class="ps-4">Name</th><th>Role</th><th>Username</th><th>Email</th><th>Status</th><th>Security</th><th>Force change</th><th class="text-end pe-4">Actions</th></tr></thead><tbody id="accountingUsersRows"><tr><td colspan="8" class="text-center py-4 text-muted">Loading…</td></tr></tbody></table></div></div></section>
 <div class="modal fade" id="officerModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form id="officerForm" novalidate><div class="modal-header"><div><h2 class="modal-title h5 mb-1" id="officerModalTitle">Add Payment User</h2><small class="text-muted">Account access is limited by the selected PMS role.</small></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="user_id"><div class="mb-3"><label class="form-label">Role</label><select class="form-select" name="role_key" required><option value="accounting_admin">Accounting Admin</option><option value="accounting_officer">Accounting Officer</option><option value="cashier">Cashier</option></select></div><div class="mb-3"><label class="form-label">Full name</label><input class="form-control" name="full_name" required></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Username</label><input class="form-control" name="username" required autocomplete="off"></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" name="email" type="email" required autocomplete="off"></div></div><div class="password-fields mt-3"><label class="form-label">Temporary password</label><input class="form-control" name="password" type="password" autocomplete="new-password"><div class="form-text">The user must replace this at first login.</div><label class="form-label mt-2">Confirm temporary password</label><input class="form-control" name="password_confirm" type="password" autocomplete="new-password"><div class="password-feedback small mt-2" aria-live="polite"></div><ul class="password-rules small text-muted ps-3 mb-0"><li data-rule="length">12–128 characters</li><li data-rule="upper">Uppercase letter</li><li data-rule="lower">Lowercase letter</li><li data-rule="number">Number</li><li data-rule="special">Special character</li><li data-rule="identifier">Does not contain username/email</li><li data-rule="match">Passwords match</li></ul></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Save User</button></div></form></div></div></div>
 <div class="modal fade" id="resetPasswordModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form id="resetPasswordForm" novalidate><div class="modal-header"><div><h2 class="modal-title h5 mb-1">Reset password</h2><small class="text-muted" id="resetPasswordTarget"></small></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="user_id"><div class="alert alert-info small"><i class="fas fa-shield-alt me-1"></i>This creates a temporary password. The user must change it on next login.</div><label class="form-label">New temporary password</label><input class="form-control" name="password" type="password" autocomplete="new-password" required><label class="form-label mt-3">Confirm password</label><input class="form-control" name="password_confirm" type="password" autocomplete="new-password" required><div class="password-feedback small mt-2" aria-live="polite"></div><ul class="password-rules small text-muted ps-3 mb-0"><li data-rule="length">12–128 characters</li><li data-rule="upper">Uppercase letter</li><li data-rule="lower">Lowercase letter</li><li data-rule="number">Number</li><li data-rule="special">Special character</li><li data-rule="identifier">Does not contain username/email</li><li data-rule="match">Passwords match</li></ul></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-warning">Reset password</button></div></form></div></div></div>
</main>
<script src="<?= BASE_URL ?>/modules/payment/assets/js/accounting-user-management.js"></script>
<?php require_once ROOT_PATH . '/includes/layout-end.php'; ?>
