<?php
declare(strict_types=1);
require_once __DIR__ . '/../../../../config/config.php';
require_once ROOT_PATH . '/includes/authentication.php';
requireAuth();
requirePaymentPermission('payment_users.view');
$pageTitle = 'Payment Users';
$activeModule = 'payment';
$activePage = 'mis_admin/payment-user-management';
$breadcrumbs = [['label' => 'MIS Admin', 'url' => BASE_URL . '/modules/payment/pages/mis_admin/dashboard.php'], ['label' => 'Payment Users', 'url' => null]];
require_once ROOT_PATH . '/includes/breadcrumbs.php';
require_once ROOT_PATH . '/includes/layout-start.php';
renderBreadcrumbs($breadcrumbs);
?>
<link rel="stylesheet" href="<?= BASE_URL ?>/modules/payment/assets/css/payment-mis-admin.css?v=1">
<main class="container-fluid py-4" id="accountingUsersApp"
 data-api="<?= htmlspecialchars(BASE_URL . '/modules/payment/api/mis_admin/payment-users.php', ENT_QUOTES, 'UTF-8') ?>"
 data-csrf="<?= htmlspecialchars(csrfToken(), ENT_QUOTES, 'UTF-8') ?>"
 data-can-create="<?= paymentRoleAllowsPermission(getCurrentUserRoleKey(), 'payment_users.create') ? '1' : '0' ?>"
 data-can-update="<?= paymentRoleAllowsPermission(getCurrentUserRoleKey(), 'payment_users.update') ? '1' : '0' ?>"
 data-can-assign-role="<?= paymentRoleAllowsPermission(getCurrentUserRoleKey(), 'payment_users.role.assign') ? '1' : '0' ?>"
 data-can-activate="<?= paymentRoleAllowsPermission(getCurrentUserRoleKey(), 'payment_users.activate') ? '1' : '0' ?>"
 data-can-deactivate="<?= paymentRoleAllowsPermission(getCurrentUserRoleKey(), 'payment_users.deactivate') ? '1' : '0' ?>"
 data-can-unlock="<?= paymentRoleAllowsPermission(getCurrentUserRoleKey(), 'payment_users.unlock') ? '1' : '0' ?>"
 data-can-reset-password="<?= paymentRoleAllowsPermission(getCurrentUserRoleKey(), 'payment_users.password.reset') ? '1' : '0' ?>">
 <div class="mis-page-header"><div><h1 class="h3">Payment Users</h1><p>Manage authorized Payment personnel accounts and access states.</p></div><?php if (paymentRoleAllowsPermission(getCurrentUserRoleKey(), 'payment_users.create')): ?><button class="btn btn-primary" id="newOfficer">Add Payment User</button><?php endif; ?></div>
 <div id="accountingUsersMessage" class="mis-async-state" role="status" aria-live="polite"></div>
 <section class="card mis-table-card"><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th scope="col" class="ps-4">Name</th><th scope="col">Role</th><th scope="col">Username</th><th scope="col">Email</th><th scope="col">Status</th><th scope="col">Security</th><th scope="col">Force change</th><th scope="col" class="text-end pe-4">Actions</th></tr></thead><tbody id="accountingUsersRows"><tr><td colspan="8" class="text-center py-4 text-muted">Loading Payment users…</td></tr></tbody></table></div></div></section>
 <div class="modal fade" id="officerModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form id="officerForm" novalidate><div class="modal-header"><div><h2 class="modal-title h5 mb-1" id="officerModalTitle">Add Payment User</h2><small class="text-muted">Account access is limited by the selected PMS role.</small></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close dialog"></button></div><div class="modal-body"><input type="hidden" name="user_id"><div class="mb-3"><label class="form-label" for="paymentUserRole">Role</label><select id="paymentUserRole" class="form-select" name="role_key" required><option value="accounting_admin">Accounting Admin</option><option value="accounting_officer">Accounting Officer</option><option value="cashier">Cashier</option></select></div><div class="mb-3"><label class="form-label" for="paymentUserName">Full name</label><input id="paymentUserName" class="form-control" name="full_name" required></div><div class="row g-3"><div class="col-md-6"><label class="form-label" for="paymentUsername">Username</label><input id="paymentUsername" class="form-control" name="username" required autocomplete="off"></div><div class="col-md-6"><label class="form-label" for="paymentUserEmail">Email</label><input id="paymentUserEmail" class="form-control" name="email" type="email" required autocomplete="off"></div></div><div class="password-fields mt-3"><label class="form-label" for="paymentTempPassword">Temporary password</label><input id="paymentTempPassword" class="form-control" name="password" type="password" autocomplete="new-password"><div class="form-text">The user must replace this at first login.</div><label class="form-label mt-2" for="paymentTempPasswordConfirm">Confirm temporary password</label><input id="paymentTempPasswordConfirm" class="form-control" name="password_confirm" type="password" autocomplete="new-password"><div class="password-feedback small mt-2" aria-live="polite"></div><ul class="password-rules small text-muted ps-3 mb-0"><li data-rule="length">12–128 characters</li><li data-rule="upper">Uppercase letter</li><li data-rule="lower">Lowercase letter</li><li data-rule="number">Number</li><li data-rule="special">Special character</li><li data-rule="identifier">Does not contain username/email</li><li data-rule="match">Passwords match</li></ul></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Save User</button></div></form></div></div></div>
 <div class="modal fade" id="resetPasswordModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form id="resetPasswordForm" novalidate><div class="modal-header"><div><h2 class="modal-title h5 mb-1">Reset password</h2><small class="text-muted" id="resetPasswordTarget"></small></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close dialog"></button></div><div class="modal-body"><input type="hidden" name="user_id"><div class="alert alert-info small"><i class="fas fa-shield-alt me-1"></i>This creates a temporary password. The user must change it on next login.</div><label class="form-label" for="resetTempPassword">New temporary password</label><input id="resetTempPassword" class="form-control" name="password" type="password" autocomplete="new-password" required><label class="form-label mt-3" for="resetTempPasswordConfirm">Confirm password</label><input id="resetTempPasswordConfirm" class="form-control" name="password_confirm" type="password" autocomplete="new-password" required><div class="password-feedback small mt-2" aria-live="polite"></div><ul class="password-rules small text-muted ps-3 mb-0"><li data-rule="length">12–128 characters</li><li data-rule="upper">Uppercase letter</li><li data-rule="lower">Lowercase letter</li><li data-rule="number">Number</li><li data-rule="special">Special character</li><li data-rule="identifier">Does not contain username/email</li><li data-rule="match">Passwords match</li></ul></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-warning">Reset password</button></div></form></div></div></div>
</main>
<script src="<?= BASE_URL ?>/modules/payment/assets/js/accounting-user-management.js"></script>
<?php require_once ROOT_PATH . '/includes/layout-end.php'; ?>
