<?php
declare(strict_types=1);
require_once __DIR__.'/../../../../config/config.php';
require_once ROOT_PATH.'/includes/authentication.php';
requireAuth();
requirePaymentPermission('payment.permissions.manage');
$pageTitle='Roles & Permissions'; $activeModule='payment'; $activePage='mis_admin/roles-permissions';
$breadcrumbs=[['label'=>'MIS Admin','url'=>BASE_URL.'/modules/payment/pages/mis_admin/overview.php'],['label'=>'Roles & Permissions','url'=>null]];
require_once ROOT_PATH.'/includes/breadcrumbs.php'; require_once ROOT_PATH.'/includes/layout-start.php'; renderBreadcrumbs($breadcrumbs);
?>
<link rel="stylesheet" href="<?= BASE_URL ?>/modules/payment/assets/css/payment-mis-admin.css?v=5">
<main class="container-fluid payment-page py-4" id="permissionMatrixApp" data-api="<?= htmlspecialchars(BASE_URL.'/modules/payment/api/mis_admin/role-permissions.php',ENT_QUOTES,'UTF-8') ?>" data-update-api="<?= htmlspecialchars(BASE_URL.'/modules/payment/api/mis_admin/role-permission-update.php',ENT_QUOTES,'UTF-8') ?>" data-csrf="<?= htmlspecialchars(generateCsrfToken(),ENT_QUOTES,'UTF-8') ?>" aria-busy="true">
<div class="payment-page-header"><div class="payment-page-header-text"><h1 class="h3 payment-page-title">Roles &amp; Permissions</h1><p>Configure Payment module and action access within each role's fixed authority ceiling.</p></div><div class="payment-page-actions"><a class="btn btn-outline-primary" href="payment-user-management.php"><i class="fas fa-users me-1"></i>Manage Staff</a><button class="btn btn-outline-secondary" id="permissionRefresh" type="button"><i class="fas fa-rotate me-1"></i>Refresh</button></div></div>
<div class="alert alert-info border-0 shadow-sm small"><i class="fas fa-shield-halved me-2"></i>Changes apply to existing sessions on their next authorization check. Role ceilings, protected MIS access, CSRF validation, and concurrent edit checks are enforced by the server.</div>
<div id="permissionNotice" class="d-none" role="status" aria-live="polite"></div><div class="btn-group flex-wrap mb-3" id="permissionRoleTabs" role="group" aria-label="Permission role view"></div><div class="row g-3 mb-4" id="permissionSummary"><div class="col-12 text-muted">Loading authorization summary...</div></div>
<section id="permissionAllView" class="card mis-table-card d-none"><div class="card-header bg-body fw-semibold">Module access comparison</div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead id="permissionModuleHead"></thead><tbody id="permissionModuleRows"></tbody></table></div></div></section>
<section id="permissionRoleView" class="d-none"><h2 class="h5 mb-3" id="permissionRoleHeading"></h2><form class="mis-filter-bar row g-3 align-items-end mb-3" id="permissionFilters"><div class="col-md-4"><label class="form-label" for="permissionModule">Module</label><select class="form-select" id="permissionModule"><option value="">All modules</option></select></div><div class="col-md-5"><label class="form-label" for="permissionSearch">Capability</label><input class="form-control" id="permissionSearch" type="search" maxlength="100" placeholder="Search module, capability, or key"></div><div class="col-md-3 mis-filter-actions"><button class="btn btn-primary" type="submit">Apply</button><button class="btn btn-outline-secondary" id="permissionResetFilter" type="button">Reset</button></div></form><div id="permissionEditor"></div><nav class="mt-3" aria-label="Permission module pages"><ul class="pagination pagination-sm" id="permissionRolePagination"></ul></nav><div class="sticky-bottom bg-body border-top py-3 mt-3 d-flex flex-wrap align-items-center justify-content-between gap-2"><span class="small text-muted" id="permissionDirtyCount">No unsaved changes.</span><div class="d-flex gap-2"><button class="btn btn-outline-secondary" id="permissionResetChanges" type="button">Reset changes</button><button class="btn btn-outline-primary" id="permissionPreview" type="button">Preview</button><button class="btn btn-primary" id="permissionSave" type="button">Save permissions</button></div></div></section>
</main>
<div class="modal fade" id="permissionPreviewModal" tabindex="-1" aria-labelledby="permissionPreviewTitle" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-5" id="permissionPreviewTitle">Review permission changes</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><p class="text-muted small" id="permissionPreviewRole"></p><div id="permissionPreviewRows"></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Continue editing</button><button type="button" class="btn btn-primary" id="permissionConfirmSave">Confirm and save</button></div></div></div></div>
<script src="<?= BASE_URL ?>/modules/payment/assets/js/payment-role-permissions.js?v=4"></script>
<?php require_once ROOT_PATH.'/includes/layout-end.php'; ?>
